### PR TITLE
jobtap: fix issues at restart with dependent jobs

### LINKED ISSUE #6773: jobtap: jobs get errors from `job.new` with little detail on system instance restart
On Tuolumne, we saw the following errors from a series of jobs on restart. Unfortunately, there's no detail on which plugin or what exactly when wrong:
```
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaLiDPURyR, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaLhy5FNAK, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMYqd8DdH, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMYcwnMrF, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMYMZHpCf, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMY5MMfY3, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMXniDj5Z, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMXY6CotK, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMXJ2octf, new): No such file or directory
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap: job.new: callback returned error
Apr 15 09:18:12 tuolumne1 flux[38645]: job-manager.err[0]: jobtap_call (id=fnaMX45LP2P, new): No such file or directory
```

At least one affected job seemed to have an issue where duplicate `dependency-add` events were found in the eventlog:
```
[Apr07 11:53] submit userid=XXXX urgency=16 flags=0 version=1
[  +0.032349] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.032412] jobspec-update attributes.system.bank="guests" attributes.system.project="*"
[  +0.032465] validate
[Apr15 08:17] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.011328] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.013017] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.018701] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.025518] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.039838] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.042812] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.048454] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.052989] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.058903] dependency-add description="after-finish=fnaLhy5FNAK"
[  +0.082160] dependency-add description="after-finish=fnaLhy5FNAK"
[repeats many, many more times]
```

The affected job then could not have its dependency successfully removed:

```
[Apr16 01:44] dependency-remove description="after-finish=fnaLhy5FNAK"
[  +0.000023] depend
[  +0.001127] jobspec-update attributes.system.bank="guests"
[  +0.001134] priority priority=4610
[  +0.001206] exception type="dependency" severity=0 note="Failed to remove dependency after-finish=fnaLhy5FNAK" userid=767
[  +0.001252] clean
```
```

### PR DESCRIPTION
**Pull request by grondo**
This PR addresses the reproducible issues described in #6773 by preventing jobs from being iterated multiple times during job manager restart. 

Also, a commit is added to prevent multiple `dependency-add` events in a job eventlog. This is necessary because dependency plugins are called in the same manner during restart as when the job is submitted. Rather than trying to force dependency plugins to detect this condition, we just make `flux_jobtap_dependency_add(3)` detect existing identical dependencies and prevent the event.

Fixes #6773

### CODE REVIEW

File: src/modules/job-manager/jobtap.c [hunk 1]
```diff
@@ -1918,6 +1918,10 @@ static int jobtap_emit_dependency_event (struct jobtap *jobtap,
         errno = EINVAL;
         return -1;
     }
+    /* Avoid duplicate dependency-add events on restart
```
Comment (wihobbs) [inline src/modules/job-manager/jobtap.c:1921]: Commit nit: "One request" -> "On request"

**Review by wihobbs — APPROVED** [review]
Working on the reproducer was a lot of fun. Thanks for sharing your edits with me! Nice work, @grondo.

**Comment by grondo** [comment]
Thanks @wihobbs! Fixed that typo and will set MWP.
