### PR TITLE
 wreck: add wreck plugin for spectrum MPI 

### LINKED ISSUE #1382: flux PMI will not init spectrum MPI
See below:

```
scogland at sierra4358 in ~/expariments  (FLUX:local:///var/tmp/flux-PWuPz2)
$ flux wreckrun -n 4 ./a.out
2018-03-23T16:35:24.298395Z sched.err[0]: job 3 bad state transition from reserved to starting
2018-03-23T16:35:24.298414Z sched.err[0]: callback returns an error
2018-03-23T16:35:24.298431Z sched.err[0]: job_state_cb: failed to invoke callbacks
2018-03-23T16:35:24.360057Z sched.err[0]: job 3 bad state transition from reserved to running
2018-03-23T16:35:24.360075Z sched.err[0]: callback returns an error
2018-03-23T16:35:24.360092Z sched.err[0]: job_state_cb: failed to invoke callbacks
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sierra4358:79265] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
2018-03-23T16:35:24.441870Z sched.err[0]: job 3 bad state transition from reserved to complete
2018-03-23T16:35:24.441888Z sched.err[0]: callback returns an error
2018-03-23T16:35:24.441904Z sched.err[0]: job_state_cb: failed to invoke callbacks
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sierra4358:79266] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sierra4358:79267] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /__SMPI_build_dir____________________________________________/exports/optimized/share/spectrum_mpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sierra4358:79264] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
wreckrun: tasks [0-3]: exited with exit code 1

```

### LINKED ISSUE #1584: wreck: add plugin for spectrum MPI
As discussed in #1382, it would be useful to add an "MPI plugin" for spectrum MPI so that a user can launch spectrum MPI jobs with `flux wreckrun  -o mpi=spectrum`. 

@grondo added some support for this in #1578.

In the comments for issue #1576 (closed by the above) there was further discussion of how to write this plugin.

In #1382, I think this was the most recent set of runes that worked for @trws?
```
OMPI_MCA_osc=pt2pt \
OMPI_MCA_pml=yalla \
OMPI_MCA_btl=self \
MPI_ROOT=/opt/ibm/spectrum_mpi \
OPAL_LIBDIR=/opt/ibm/spectrum_mpi/lib \
flux wreckrun -N 4 env \
LD_LIBRARY_PATH=/opt/ibm/spectrum_mpi/lib/pami_port:/opt/ibm/spectrum_mpi/lib:/opt/ibm/spectrum_mpi/lib:/opt/mellanox/hcoll/lib OMPI_MCA_coll_hcoll_enable=0 \
bash -c 'ulimit -s 10240 ; \
env LD_PRELOAD=/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so \
~/flux-base/mpitest-spectrum 
```

### PR DESCRIPTION
**Pull request by SteVwonder**
Add support for spectrum MPI on Sierra via optional wreck plugin.
Activated by calling `wreckrun` or `submit` with `-o mpi=spectrum`.

Credit goes to @grondo and @garlick.

Closes #1584 
Closes #1382

### CODE REVIEW

**Comment by SteVwonder** [comment]
Not sure how to test this with the CI other than maybe checking that the environment variables and stack limit were set.  Thoughts?

**Comment by grondo** [comment]
Yes, that would be  a good sanity check IMO

File: src/modules/wreck/lua.d/spectrum.lua [hunk 1]
```diff
@@ -0,0 +1,47 @@
+-- Set environment specific to spectrum_mpi (derived from openmpi)
```
Comment (garlick) [inline src/modules/wreck/lua.d/spectrum.lua]: Commit message body should be filled in.  Maybe something like

> Add mpi "personality" for IBM spectrum MPI, enabled by user with wreckrun -o mpi-spectrum.
> Note that this plugin assumes MPI is installed in /opt/ibm/spectrum_mpi.
> It also disables PAMI, the spectrum enhanced collectives due to their dependency on the RM providing
> a PMIx server.  See #1382 for further details.
> It also sets the soft stack limit to a value the MPI runtime seems to require.
>
> See #1382 for more details.
>
> Fixes #1584

File: src/modules/wreck/lua.d/spectrum.lua [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+    env['PMIX_SERVER_URI2'] = nil
+
+    -- help find libcollectives.so
+    prepend_path ('LD_LIBRARY_PATH', '/opt/ibm/spectrum_mpi/lib/pami_port')
+    prepend_path ('LD_PRELOAD', '/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so')
+end
+
+function rexecd_task_init ()
+    -- approximately ulimit -Ss 10240
+    posix.setrlimit ("stack", 10485760)
```
Comment (garlick) [inline src/modules/wreck/lua.d/spectrum.lua]: If we know a version of lua.posix that this doesn't work on, perhaps note it here in a comment?

Also perhaps note that this is set to shut up the spectrum MXM plugin.

**Comment by garlick** [comment]
So much nicer without all the noise!

```
$ flux wreckrun -o mpi=spectrum -n 32 ./hello
0: completed MPI_Init in 2.368s.  There are 32 tasks
0: completed first barrier in 0.002s
0: completed MPI_Finalize in 0.218s
```

That was a single node test.  Let me try one across nodes.

**Comment by garlick** [comment]
Within a bsub allocation obtained with
```
$ bsub -Is -nnodes 4 -G guests /usr/bin/bash
```
I ran a script containing:
```
#!/bin/bash
jsrun -a 40 -c ALL_CPUS --bind=none -r 1 -n 4 \
   $HOME/flux-core/src/cmd/flux start \
	flux wreckrun -o mpi=spectrum -n 128 $HOME/flux-core/t/mpi/hello
```
and got
```
... Warning: more than 1 task/rank assigned to a core 
0: completed MPI_Init in 3.283s.  There are 128 tasks
0: completed first barrier in 0.002s
0: completed MPI_Finalize in 0.335s
```
Victory!

**Comment by grondo** [comment]
Is every MPI job a spectrum MPI job on this platform? Maybe we could do better with a platform check or something so the `-o mpi=spectrum` isn't required? (Not a valid concern if there are a mix of MPIs)

**Comment by SteVwonder** [comment]
@grondo: I think everything right now is Spectrum, but I don't know if that will always be the case.
```
# herbein1 at sierra4362 in ~/workspace/packages/blueos3/flux-core/spack/etc/wreck/lua.d [10:31:58]
→ find /usr/tcetmp/modulefiles -iname "*mpi*"
/usr/tcetmp/modulefiles/Compiler
/usr/tcetmp/modulefiles/Compiler/clang/3.9.1/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/4.0.0/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.03.15/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.03.29/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.05.03/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.05.19/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.06.08/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.06.12/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/clang/coral-2017.06.14/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/gcc/4.8-redhat/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/gcc/4.9.3/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/16.10/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/17.1/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/17.3/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/17.4/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/17.7/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/pgi/17.9/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/2016.12.02/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.03.28/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.04.11/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.05.08/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.06.07/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.06.29/spectrum-mpi
/usr/tcetmp/modulefiles/Compiler/xl/beta-2017.07.28/spectrum-mpi
/usr/tcetmp/modulefiles/Core/mpifileutils
find: ‘/usr/tcetmp/modulefiles/Core/essl’: Permission denied
/usr/tcetmp/modulefiles/Core/debugCQEmpi.lua
/usr/tcetmp/modulefiles/MPI
/usr/tcetmp/modulefiles/MPI/clang/coral-2017.03.15/spectrum_mpi
/usr/tcetmp/modulefiles/MPI/gcc/4.8-redhat/spectrum_mpi
/usr/tcetmp/modulefiles/MPI/gcc/4.9.3/spectrum_mpi
/usr/tcetmp/modulefiles/MPI/xl/default/spectrum_mpi
```

File: src/modules/wreck/lua.d/spectrum.lua (hunk 1 above)
Comment (SteVwonder) [reply src/modules/wreck/lua.d/spectrum.lua]: Will do. Sorry for the sloppiness there.

File: src/modules/wreck/lua.d/spectrum.lua (hunk 2 above)
Comment (SteVwonder) [reply src/modules/wreck/lua.d/spectrum.lua]: I will look into seeing exactly when luaposix switched this interface to deprecated and add a conditional that uses the newer interface on newer luaposix libraries.

And I will add the comment about the spectrum plugin

Comment (grondo) [reply src/modules/wreck/lua.d/spectrum.lua]: If you look at `src/bindings/lua/flux/posix.lua` we already have a wrapper around the luaposix module to "work around" at least one compat issue.

You could use the same `pcall()` trick  (used in there to check for `posix.time`) to check for `posix.sys.resource` and use that module's setrlimit() instead of the one from deprecated.lua.

Comment (grondo) [reply src/modules/wreck/lua.d/spectrum.lua]: Though now that I think about it I wonder if `flux.posix` is loaded in wrexecd context... have to check on that

Comment (SteVwonder) [reply src/modules/wreck/lua.d/spectrum.lua]: I was going down the route of parsing the luaposix version string and specializing based on that version, when I realized `posix.setrlimit ("stack", 10485760, -1)` always does the right thing.  As long as we are OK using this deprecated function, there is no need for any of the version string parsing nastiness, etc.  Thoughts?

Comment (grondo) [reply src/modules/wreck/lua.d/spectrum.lua]: Does that fail if the current hard limit isn't unlimited?

Comment (SteVwonder) [reply src/modules/wreck/lua.d/spectrum.lua]: Spoke with @grondo and @garlick in person.  For the sake of getting this out the door, the existing code should be fine.  We can revisit if any problems in the wild pop up.

File: src/modules/wreck/lua.d/spectrum.lua (hunk 1 above)
Comment (SteVwonder) [reply src/modules/wreck/lua.d/spectrum.lua]: Done

File: t/t3001-mpi-personalities.t [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+OPTS="-o mpi=spectrum"
+test_expect_success "spectrum mpi sets MPI_ROOT" '
+  run_program 5 ${SIZE} ${SIZE} printenv MPI_ROOT \
+  	| tee spectrum-mpi.env \
+    && test "$(uniq spectrum-mpi.env)" == "/opt/ibm/spectrum_mpi"
+'
+
+OPTS="-o mpi=spectrum"
+test_expect_success "spectrum mpi sets the soft stack limit" '
+  run_timeout 5 flux wreckrun -n ${SIZE} -N ${SIZE} $OPTS bash -c "ulimit -s" \
```
Comment (SteVwonder) [inline t/t3001-mpi-personalities.t]: I gave up trying to get the quoting of `bash -c "ulimit -s"` to play nice with  `run_program`.  If anyone has any pointers or suggestions, I'm open to hearing them. I'm also content leaving it as is.

Comment (dongahn) [reply t/t3001-mpi-personalities.t]: `""ulimit -s""` doesn't work?

Comment (garlick) [reply t/t3001-mpi-personalities.t]: What you have seems to be working.  What's the problem?

**Comment by garlick** [comment]
LGTM (unless there is still a problem with the ulimit test).

Just needs a rebase on current master.

File: t/t3001-mpi-personalities.t (hunk 3 above)
Comment (SteVwonder) [reply t/t3001-mpi-personalities.t]: Unfortunately not.
`"ulimit -s"` and `""ulimit -s""` both result in the `-s` not being passed to ulimit.
If I put an `echo` in front of the `run_timeout ...` call in `run_program` and then test various quotings, I get:
```
run_timeout 5 flux wreckrun -o mpi=spectrum -n17 -N17 bash -c ulimit -s
run_timeout 5 flux wreckrun -o mpi=spectrum -n17 -N17 bash -c ulimit -s
run_timeout 5 flux wreckrun -o mpi=spectrum -n17 -N17 bash -c 'ulimit -s'
run_timeout 5 flux wreckrun -o mpi=spectrum -n17 -N17 bash -c 'ulimit -s'
```
from these:
```
OPTS="-o mpi=spectrum"
test_expect_success "spectrum mpi sets MPI_ROOT" '                                                                                                                                                 
  run_program 5 ${SIZE} ${SIZE} bash -c "ulimit -s"                                                                                                                                             
'

OPTS="-o mpi=spectrum"
test_expect_success "spectrum mpi sets MPI_ROOT" '                                                                                                                                                 
  run_program 5 ${SIZE} ${SIZE} bash -c ""ulimit -s""                                                                                                                                               
'

CMD="bash -c 'ulimit -s'"
OPTS="-o mpi=spectrum"
test_expect_success "spectrum mpi sets MPI_ROOT" '                                                                                                                                                 
  run_program 5 ${SIZE} ${SIZE} ${CMD}                                                                                                                                               
'

CMD="bash -c 'ulimit -s'"
OPTS="-o mpi=spectrum"
test_expect_success "spectrum mpi sets MPI_ROOT" '                                                                                                                                                 
  run_program 5 ${SIZE} ${SIZE} "${CMD}"
'

```

And none of them succeed. I would have sworn that the last two would work but :man_shrugging:

Comment (dongahn) [reply t/t3001-mpi-personalities.t]: A complex case for me was https://github.com/flux-framework/flux-scalability/blob/master/t/t0001-sched-scale.t#L53 to pass single quotes to awk. Don't know if this will be helpful.

Comment (dongahn) [reply t/t3001-mpi-personalities.t]: ?
```
test_expect_success "spectrum mpi sets the soft stack limit" '
    run_timeout 5 flux wreckrun -n ${SIZE} -N ${SIZE} $OPTS bash -c '\''ulimit -s'\'
'

Comment (SteVwonder) [reply t/t3001-mpi-personalities.t]:
```
OPTS="-o mpi=spectrum"
test_expect_success "spectrum mpi sets the soft stack limit" '                                                                                                                                     
  run_program 5 ${SIZE} ${SIZE} bash -c '\''ulimit -s'\'' \                                                                                                                                        
    | tee spectrum-mpi.ulimit \                                                                                                                                                                    
    && test "$(uniq spectrum-mpi.ulimit)" = "10240"                                                                                                                                                
'
```
results in
```
run_timeout 5 flux wreckrun -o mpi=spectrum -n17 -N17 bash -c ulimit -s
```
and the incorrect result.

My bash-fu isn't good enough to know what is really going on but I think the `$*` in `run_program` is what is changing the quoting.

**Comment by SteVwonder** [comment]
Ok. I just forced push a fix for an error on Travis in the tests: `test "string" = "string"` rather than `test "string" == "string"`, and then I rebased.

Have a great weekend guys!

File: t/t3001-mpi-personalities.t (hunk 3 above)
Comment (grondo) [reply t/t3001-mpi-personalities.t]: Using double quote inside of single-quoted test script works in other sharness tests in the testsuite, see the wreck and aggregator tests, and I think some kvs tests too.

I wonder what is going wrong here.

Comment (grondo) [reply t/t3001-mpi-personalities.t]: > If I put an echo in front of the run_timeout ... call in run_program and then test various quotings, I get:

But the `echo` doesn't necessarily show the arguments (which may contain whitespace) passed down to the command.

Sometimes I resort to putting a `set -x` before the code and `set +x` after see what is actually being run.

**Comment by garlick** [comment]
Was that the problem that you thought was a quoting problem?

Is this ready to merge once travis passes?

File: t/t3001-mpi-personalities.t (hunk 3 above)
Comment (grondo) [reply t/t3001-mpi-personalities.t]: Oops, sorry for the noise, somehow my version of this issue wasn't updated with the latest comments.

**Comment by SteVwonder** [comment]
No that was a problem that caused some of Travis tests to fail. Whatever shell on Sierra was running the tests was content with the `==` but the shell on Travis wasn't a fan.  So all of the non-coverage tests failed.  Looks like one of the tests is still failing.  Lemme take a look. I'll try and push a fix tonight.

File: t/t3001-mpi-personalities.t (hunk 3 above)
Comment (SteVwonder) [reply t/t3001-mpi-personalities.t]: > Sometimes I resort to putting a set -x before the code and set +x after see what is actually being run.

Thanks @grondo. I'll give that a shot.

**Comment by garlick** [comment]
Here's a discussion on `=` vs `==`:  https://unix.stackexchange.com/questions/382003/what-are-the-differences-between-and-in-conditional-expressions

I can't remember the original reason, but the other bash scripts use `#!/bin/sh` (and do not assume it's linked to bash as it is on some systems).  At  this point it's probably best to continue that convention for consistency.

**Comment by grondo** [comment]
> I can't remember the original reason, but the other sharness scripts use #!/bin/sh (and do not assume it's linked to bash as it is on some systems). 

The original git testsuite instructed all tests to begin with `#!/bin/sh`, and this is carried forward in sharness. In upstream sharness PRs, bashisms in scripts are rejected. 

https://github.com/chriscool/sharness/blob/master/README.git#L221

**Comment by SteVwonder** [comment]
@grondo: thanks for pointing out the `check_lint` flag.  That seems to have been the problem :smile: 
Just rebased on master. Hopefully Travis turns all green now.

**Comment by garlick** [comment]
Looks good, hash bang fixed, `t3001-mpi-personalities.t --chain-lint` now passing for me.

Ready to merge once travis passes?

**Comment by SteVwonder** [comment]
Yep. :grin: I'm happy with this once Travis is happy.

**Comment by garlick** [comment]
Nice work @SteVwonder.
