### PR TITLE
wrexecd: move sending of wreck.state.complete event after job archival

### LINKED ISSUE #728: Wreck job archival causes a race condition
I am currently experiencing what I believe to be a race condition with the job archival.

The simulator inserts information into the kvs about jobs after they have completed.  In a non-deterministic manner, some of the jobs never have this information inserted into their KVS directories.  I assumed that this was do to a race condition with the job archival and the put, so I ending up writing my own archive job function that moves a directory, commits, and then tries to put into the new directory (followed by a commit).  It pretty consistently fails (the fail is silent, as the information never makes it into the directory).  If I add a sleep of 1 second after the 1st commit, it succeeds more often.  If I lump the move and the put into a single commit, it fails just as frequently.

Any thoughts? I am not sure if this expected behavior or not.  I can try making a small reproducer if it would help.

### PR DESCRIPTION
**Pull request by SteVwonder**
Closes #728

### CODE REVIEW

**Comment by grondo** [comment]
This looks good to me, thanks!

@SteVwonder, would you be willing to flesh out the commit message a bit before we merge? E.g. shorten the title to 50 chars, then in the commit message body describe the issue and the resulting solution for posterity? Thanks.

Also I have just a couple very minor line comments I'll add presently to the commit. All very minor and not critical IMO.

File: src/modules/wreck/wrexecd.c [hunk 1]
```diff
@@ -2382,24 +2383,24 @@ int main (int ac, char **av)
...
 
-        if (flux_reactor_run (flux_get_reactor (ctx->flux), 0) < 0)
-            wlog_err (ctx, "flux_reactor_run: %s", flux_strerror (errno));
-
-        rexec_state_change (ctx, "complete");
-        wlog_msg (ctx, "job complete. exiting...");
-
-        lua_stack_call (ctx->lua_stack, "rexecd_exit");
-    }
+    if (!exec_rc && flux_reactor_run (flux_get_reactor (ctx->flux), 0) < 0)
```
Comment (grondo) [inline src/modules/wreck/wrexecd.c]: For some reason `if (!exec_rc ..` confused me for a second here, would you be willing to change to `if (exec_rc == 0 &&` for clarity? Might just be me though...

File: src/modules/wreck/wrexecd.c [hunk 2]
```diff
@@ -2382,24 +2383,24 @@ int main (int ac, char **av)
...
 
     if (ctx->nodeid == 0) {
         /* At final job state, archive the completed lwj back to the
          * its final resting place in lwj.<id>
          */
         if (archive_lwj (ctx) < 0)
             wlog_err (ctx, "archive_lwj failed");
+    }
 
+    if (!exec_rc) {
```
Comment (grondo) [inline src/modules/wreck/wrexecd.c]: Same as above, I'd prefer `if (exec_rc == 0)`

File: src/modules/wreck/wrexecd.c (hunk 1 above)
Comment (lipari) [inline src/modules/wreck/wrexecd.c]: @grondo, if this is to be a convention to follow, it should be added to [RFC 7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc).  I use `if (something)` all the time.  And I readily recognize it as a shortcut for `if (something != 0)`.  Similarly `if (!something)` is a valid shortcut for `if (something == 0)` - at least to my eyes anyway.

Comment (grondo) [inline src/modules/wreck/wrexecd.c]: Yes, it is technically valid. However, In cases like this where `rc < 0` means failure and `rc == 0` means success, I find use of `if (rc)` and `if (!rc)` a possible source for confusion because my brain tends to promote the variable to a boolean --  moreso when the test is split from the call site and I may have lost a modicum of context.. In this specific case the the line reads as "if *not* exec_rc" which is much more confusing to me than "if exec_rc is zero".

However, I'm willing to admit this could be my personal hangup and it doesn't matter enough to block merge of this PR.

**Comment by SteVwonder** [comment]
@grondo: I modified those if statements to include the more explicit `== 0`.  I also updated the commit message and rebased.

**Comment by grondo** [comment]
@SteVwonder: great thanks, merging!
