### PR TITLE
librouter: avoid dropping messages on EPIPE

### LINKED ISSUE #2906: not ok 31 - flux-terminus: copy stdin
From a travis run failure in #2902 

It appears that the remote pty shell got the `exit` command, but the client never exited, or did not print `detached`. Not sure what could have gone wrong there at this point, may have to add more debug to this test or try to reproduce.

```
expecting success: 
	$runpty -o log.pipe-stdin flux terminus start &
	pid=$! &&
	$waitfile -t 20 -v -p \"o\" log.pipe-stdin &&
	printf "echo hello\r" | flux terminus attach -p 0 &&
	$waitfile -t 20 -v -p hello log.pipe-stdin &&
	printf "exit\r" | flux terminus attach -p 0 &&
	$waitfile -t 20 -v -p detached log.pipe-stdin &&
	wait $pid

waitfile: log.pipe-stdin: 0.000s: No file yet
waitfile: log.pipe-stdin: 0.251s: wakeup
waitfile: log.pipe-stdin: 0.251s: File appeared with size 322
waitfile: log.pipe-stdin: 0.251s: log.pipe-stdin seek set to 0
waitfile: log.pipe-stdin: 0.251s: Got match (1/1)
waitfile: log.pipe-stdin: 0.251s: Got match. Calling self:on_match()
waitfile: log.pipe-stdin: 0.251s: Exiting
{"version": 2, "width": 80, "height": 25, "timestamp": 1587600020}
[0.03823256492614746, "o", "\u001b[2J\u001b[;H"]
waitfile: log.pipe-stdin: 0.000s: File appeared with size 399
waitfile: log.pipe-stdin: 0.000s: log.pipe-stdin seek set to 0
waitfile: log.pipe-stdin: 0.000s: Got match (1/1)
waitfile: log.pipe-stdin: 0.000s: Got match. Calling self:on_match()
waitfile: log.pipe-stdin: 0.000s: Exiting
{"version": 2, "width": 80, "height": 25, "timestamp": 1587600020}
[0.03823256492614746, "o", "\u001b[2J\u001b[;H"]
[0.042634010314941406, "o", "To run a command as administrator (user \"root\"), use \"sudo <command>\".\r\nSee \"man sudo_root\" for details.\r\n\r\n"]
[0.04330277442932129, "o", "travis@6e01950176fc:~$ "]
[0.20807552337646484, "o", "echo hello\r\nhello\r\ntravis@6e01950176fc:~$ "]
waitfile: log.pipe-stdin: 0.000s: File appeared with size 476
waitfile: log.pipe-stdin: 0.000s: log.pipe-stdin seek set to 0
waitfile: log.pipe-stdin: 0.000s: leaving checklines() position=476
waitfile: log.pipe-stdin: 20.018s: Timeout after 20s
-rw-r--r-- 1 travis travis 476 Apr 23 00:00 log.pipe-stdin
{"version": 2, "width": 80, "height": 25, "timestamp": 1587600020}
[0.03823256492614746, "o", "\u001b[2J\u001b[;H"]
[0.042634010314941406, "o", "To run a command as administrator (user \"root\"), use \"sudo <command>\".\r\nSee \"man sudo_root\" for details.\r\n\r\n"]
[0.04330277442932129, "o", "travis@6e01950176fc:~$ "]
[0.20807552337646484, "o", "echo hello\r\nhello\r\ntravis@6e01950176fc:~$ "]
[0.2577371597290039, "o", "exit\r\nexit"]
[0.25838804244995117, "o", "\r\n"]
not ok 31 - flux-terminus: copy stdin
```

### PR DESCRIPTION
**Pull request by grondo**
As described in #2931, there is a potential for dropping messages from api socket clients that write messages and immediately exit or call `flux_close()`. This happens if the connector-local module (a usock_server) gets EPIPE writing messages *to* a client before it reads pending messages *from* the client. The connection is immediately torn down in this case instead of reading any pending data from the client.

This patch adds specific handling for EPIPE. <essages to the client are dropped and the output watcher is stopped, but the connection is not destroyed until EOF/ECONNRESET is received when *reading* from the client. (I think this is guaranteed since we don't have partial close).

It took a bit to come up with a good reproducer. In order to synchronize properly in the tests, I had to add a "close callback" for `struct usock_server`. Not sure if that was the right approach. I did verify that without this patch, the reproducer catches the issue. The output from the test in that case looks like:

```
ok 12 - usock_client_connect /tmp/usock.XaDHNp9/server works
ok 13 - usock_client_create works
ok 14 - usock_client_send init message works: expected=5
ok 15 - usock_client_send[1] works
ok 16 - usock_client_send[2] works
ok 17 - usock_client_send[3] works
ok 18 - connection: uuid=4bb70: expect 5 messages
ok 19 - usock_client_send[4] works
# disconnecting
# server_error_cb uuid=4bb70: Broken pipe
# server_close_cb: uuid=4bb70: recvd 3/5 messages
not ok 20 - got 3/5 messages
#   Failed test 'got 3/5 messages'
#   at test/usock_epipe.c line 228.
```

Also:

Fixes #2906

### CODE REVIEW

**Comment by grondo** [comment]
Hm, looks like the test may yet need a little more work.

File: src/common/librouter/test/usock_epipe.c [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+
+    diag ("starting test server");
+    test_server_environment_init ("usock_server");
+
+    if (!(h = test_server_create (server_cb, &tp)))
+        BAIL_OUT ("test_server_create failed");
+
+    pthread_mutex_lock (&server_mutex);
+    test_send_and_exit (h, 1);
+    pthread_mutex_lock (&server_mutex);
```
Comment (garlick) [inline src/common/librouter/test/usock_epipe.c:214]: Is it the case that the client thread only locks the mutex and the server thread only unlocks the mutex?  So the client thread is expected to block trying to retake the mutex?  I think that's a problem...

From [pthread_mutex_settype(3)](https://linux.die.net/man/3/pthread_mutexattr_settype):

> PTHREAD_MUTEX_DEFAULT
> Attempting to recursively lock a mutex of this type results in undefined behavior. Attempting to unlock a mutex of this type which was not locked by the calling thread results in undefined behavior. Attempting to unlock a mutex of this type which is not locked results in undefined behavior. An implementation may map this mutex to one of the other mutex types.

Might want a condition variable here.

Comment (grondo) [reply src/common/librouter/test/usock_epipe.c:214]: Bah, you're right. I was trying to be lazy as possible and failed.

Comment (garlick) [reply src/common/librouter/test/usock_epipe.c:214]: We should all give being lazy our best effort :-)

Comment (grondo) [reply src/common/librouter/test/usock_epipe.c]: Ok I pushed a fixup switching to a condition variable. Hopefully I did it correctly as it has been awhile.

It occurred to me that using pthread synchronization is not the zeromq nor "Flux" way to do things between client and server. Ideally the server would store test results that could then be "fetched" by the client (test main) to check whether any messages were dropped.

File: src/common/librouter/test/usock_epipe.c [hunk 2]
```diff
@@ -99,9 +100,12 @@ static void server_error_cb (struct usock_conn *conn, int errnum, void *arg)
 static void server_close_cb (struct usock_conn *conn, void *arg)
 {
     struct test_params *tp = arg;
+    tp->ready = 1;
```
Comment (garlick) [inline src/common/librouter/test/usock_epipe.c:103]: I'm rusty too, so might be wrong, but should `tp->ready` be modified with the mutex held?

Comment (grondo) [reply src/common/librouter/test/usock_epipe.c:103]: Heh, yeah. duh. :roll_eyes:

Comment (grondo) [reply src/common/librouter/test/usock_epipe.c:103]: Mind if I fix, squash, and force-push?

Comment (garlick) [reply src/common/librouter/test/usock_epipe.c:103]: Sure!

**Comment by grondo** [comment]
ASan check build failed here:
```
FAIL: t0001-basic.t 33 - tbon.parent-endpoint cannot be read on rank 0
#	
#		test_must_fail flux start -s2 flux getattr tbon.parent-endpoint
#	
ok 34 - tbon.parent-endpoint can be read on not rank 0
```

Restarting.

**Comment by grondo** [comment]
Thanks!
