### PR TITLE
ensure flux utilities agree that a job with a fatal exception has failed

### LINKED ISSUE #5307: flux job attach and flux jobs show job with fatal exception as successful
Problem: when a jobtap plugin raises a fatal exception from the `job.event.alloc` callback, the job might still run to completion and be declared successful by `flux job attach` and `flux jobs`.

Note: `flux job wait` identifies the job as failed.

See #5304

### PR DESCRIPTION
**Pull request by grondo**
As pointed out in #5307, `flux job attach` and `flux jobs` ignore fatal job exceptions if the job has a `finish` event with exit status `0`. This doesn't agree with `flux job wait` and `flux job status`, which exit with failure for any fatal job exception.

Given that a fatal exception by definition probably indicates that the job has failed in some way regardless if the job tasks finished successfully, update the behavior of these commands (as well as `flux submit` and `flux bulksubmit`) to exit with failure for any fatal job exception. Additionally, `flux jobs` now only reports a successful job if the job finished with `status=0` _and_ there were no fatal job exceptions.

Because the "alloc check" tests already generated the failing case here (job with fatal job exception but all tasks finish successfully with `status=0`) add checks to this test to ensure that the various utilities now agree that the job with the alloc-check exception has "failed".

Fixes #5307

### CODE REVIEW

File: src/cmd/flux-job.c [hunk 1]
```diff
@@ -1595,6 +1595,7 @@ struct attach_ctx {
     int eventlog_watch_count;
```
Comment (garlick) [inline src/cmd/flux-job.c:1595]: Commit message for "flux-job: attach: always exit nonzero on fatal job exception"

s/if all job finishes/if a job finishes/

**Review by garlick — APPROVED** [review]
LGTM!  Just one typo.

**Comment by grondo** [comment]
Thanks! Fixed the typo and will set MWP.
