### PR TITLE
cmd/flux-ping: make help output clearer

### LINKED ISSUE #3892: flux-ping: missing the required `SERVICE` argument in usage message
The usage message for `flux-ping` is only `flux-ping [OPTIONS]...`, but running with no arguments results in an error:

```
❯ docker run -ti fluxrm/flux-core:focal-v0.29.0 flux start flux ping                                                                                16:13:05 ()
Usage: flux-ping [OPTIONS]...
  -h, --help             Display this message.
  -r, --rank=RANK        Find target on a specific broker rank
  -p, --pad=N            Include in the payload a string of length N bytes
  -i, --interval=N       Specify the delay, in seconds, between successive
                         requests
  -c, --count=N          Specify the number of requests to send
  -b, --batch            Begin processing responses after all requests are sent
  -u, --userid           Include userid and rolemask in ping output
2021-10-01T23:13:07.524684Z broker.err[0]: rc2.0: flux ping Exited (rc=1) 0.0s
```

A service to ping is required:
```
❯ docker run -ti fluxrm/flux-core:focal-v0.29.0 flux start flux ping kvs                                                                            16:13:07 ()
kvs.ping pad=0 seq=0 time=1.101 ms (ff8406f5!f18e577b!bcda8348!39277526)
kvs.ping pad=0 seq=1 time=2.398 ms (ff8406f5!f18e577b!bcda8348!39277526)
^C2021-10-01T23:13:11.682098Z broker.err[0]: rc2.0: flux ping kvs Interrupt (rc=130) 1.4s
```

Doing something like `flux-module` does might be clearer:
```
❯ docker run -ti fluxrm/flux-core:focal-v0.29.0 flux start flux module -h                                                                           16:13:13 ()
Usage: flux-module COMMAND [OPTIONS]
  -h, --help             Display this message.

<snip>
```

I believe this accomplished by [this code](https://github.com/flux-framework/flux-core/blob/master/src/cmd/flux-module.c#L178) and something similar can be added to `flux-ping`.

### PR DESCRIPTION
**Pull request by chu11**
Problem: The default help output says "flux-ping [OPTIONS] ..."
which is not clear.

Solution: Update output to "flux-ping [OPTIONS] \<target\>".

Fixes #3892

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Looks good, thanks.  Want to add a quick `flux --help` test to `t0007-ping.t` to boost coverage?

**Comment by chu11** [comment]
re-pushed, adding a simple test

File: src/cmd/flux-ping.c [hunk 1]
```diff
@@ -262,6 +262,7 @@ void parse_service (const char *s, uint32_t *nodeid, char **topic)
 int main (int argc, char *argv[])
 {
     int pad_bytes;
+    char *cmdusage = "[OPTIONS] <target>";
```
Comment (grondo) [inline src/cmd/flux-ping.c:265]: Very minor, but none of our other commands (after spot checking) use the `<arg>` style like this, and even the `flux ping` man page uses `[OPTIONS] target`. Most of our commands have adopted `[OPTIONS]  TARGET` style, but I'd be fine with just matching the man page.

I'd actually be fine merging as-is, but thought I'd mention it for consistency's sake (and you know some  code janitor is going to come along in the future and change it, so might as well do it now :stuck_out_tongue_winking_eye: )

**Review by grondo — APPROVED** [review]
LGTM, Thanks! Just one suggestion inline.

File: src/cmd/flux-ping.c (hunk 1 above)
Comment (chu11) [reply src/cmd/flux-ping.c]: ahh good catch / idea, will adjust.

**Comment by chu11** [comment]
re-pushed with the tweak @grondo mentions above

**Comment by grondo** [comment]
> re-pushed with the tweak @grondo mentions above

Great! Feel free to set MWP when ready as far as I'm concerned.
