### PR TITLE
t: fix tests prone to races or timeouts on constrained systems

### LINKED ISSUE #2517: t0004-event.t: fails on a constrained system (e.g., `make -j check`)
On my home systems (running Ubuntu 19.10) if I run `make -j check`, `t0004-event.t` fails.

```
→ cat t0004-event.log 
2019-11-05T05:01:13.682243Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 17.9s
flux-start: 0 (pid 21898) exited with rc=1
ok 1 - heartbeat is received on all ranks
PASS: t0004-event.t 1 - heartbeat is received on all ranks
not ok 2 - events from rank 0 received correctly on rank 0
FAIL: t0004-event.t 2 - events from rank 0 received correctly on rank 0
#
#               run_timeout 5 \
#                 $SHARNESS_TEST_SRCDIR/scripts/event-trace.lua \
#                   testcase testcase.eof \
#                     $SHARNESS_TEST_SRCDIR/scripts/t0004-event-helper.sh 0 >trace &&
#               $SHARNESS_TEST_SRCDIR/scripts/t0004-event-helper.sh >trace.expected &&
#               test_cmp trace.expected trace
#
not ok 3 - events from rank 3 received correctly on rank 0
FAIL: t0004-event.t 3 - events from rank 3 received correctly on rank 0
#
#               run_timeout 5 \
#                 $SHARNESS_TEST_SRCDIR/scripts/event-trace.lua \
#                   testcase testcase.eof \
#                     $SHARNESS_TEST_SRCDIR/scripts/t0004-event-helper.sh $LASTRANK >trace &&
#               $SHARNESS_TEST_SRCDIR/scripts/t0004-event-helper.sh >trace.expected &&
#               test_cmp trace.expected trace
#
<snip>
# failed 2 among 15 test(s)
1..15
ERROR: t0004-event.t - exited with status 1
```

It appears to miss the first three events.  Here are the relevant contents of the trash-directory:

```
# sherbein at sealand in ~/Repositories/flux-framework/flux-core/t/trash-directory.t0004-event on git:travis-add-ubuntu-19.10 ✖︎ [21:05:21] (0) 
→ cat trace
testcase.eof

# sherbein at sealand in ~/Repositories/flux-framework/flux-core/t/trash-directory.t0004-event on git:travis-add-ubuntu-19.10 ✖︎ [21:05:23] (0) 
→ cat trace.expected 
testcase.foo
testcase.bar
testcase.baz
testcase.eof
```

If I run the test in isolation (i.e., `make check TESTS=t0004-event.t`) or manually in an instance (`flux start ./scripts/event-trace.lua testcase testcase.eof ./scripts/t0004-event-helper.sh 0`), it works as expected.

### LINKED ISSUE #2518: t2402-job-exec-dummy.t: test fails on constrained system (e.g., `make -j check`)
On my home systems (running Ubuntu 19.10) if I run make -j check, t2402-job-exec-dummy.t fails.
```
→ cat t2402-job-exec-dummy.log
<snip>
ok 4 - job-exec: job shell output sent to flux log
PASS: t2402-job-exec-dummy.t 4 - job-exec: job shell output sent to flux log
not ok 5 - job-exec: job shell failure recorded
FAIL: t2402-job-exec-dummy.t 5 - job-exec: job shell failure recorded
#
#               id=$(flux jobspec srun -N4  "test \$JOB_SHELL_RANK = 0 && exit 1" \
#                    | flux job submit) &&
#               flux job wait-event -vt 1 $id finish | grep status=256
#
not ok 6 - job-exec: status is maximum job shell exit codes
FAIL: t2402-job-exec-dummy.t 6 - job-exec: status is maximum job shell exit codes
#
#               id=$(flux jobspec srun -N4 "exit \$JOB_SHELL_RANK" | flux job submit) &&
#               flux job wait-event -vt 1 $id finish | grep status=768
<snip>
```

relevant bits for the `broker.log`:
```
2019-11-05T05:01:15.883084Z job-manager.debug[0]: submit_cb: added 1 jobs
2019-11-05T05:01:15.885593Z sched-simple.debug[0]: req: 265197453312: spec={4,4,1}
2019-11-05T05:01:15.885659Z sched-simple.debug[0]: alloc: 265197453312: rank[0-3]/core0
2019-11-05T05:01:17.364431Z job-exec.info[0]: 265197453312: 2: stdout: Running test $JOB_SHELL_RANK = 0 && exit 1
2019-11-05T05:01:17.558493Z job-exec.info[0]: 265197453312: 3: stdout: Running test $JOB_SHELL_RANK = 0 && exit 1
2019-11-05T05:01:17.565318Z job-exec.info[0]: 265197453312: 1: stdout: Running test $JOB_SHELL_RANK = 0 && exit 1
2019-11-05T05:01:17.655299Z job-exec.info[0]: 265197453312: 0: stdout: Running test $JOB_SHELL_RANK = 0 && exit 1
2019-11-05T05:01:17.663310Z sched-simple.debug[0]: free: rank[0-3]/core0
2019-11-05T05:01:17.982202Z job-manager.debug[0]: submit_cb: added 1 jobs
2019-11-05T05:01:17.983670Z sched-simple.debug[0]: req: 300345720832: spec={4,4,1}
2019-11-05T05:01:17.983734Z sched-simple.debug[0]: alloc: 300345720832: rank[0-3]/core0
2019-11-05T05:01:19.390887Z job-exec.info[0]: 300345720832: 2: stdout: Running exit $JOB_SHELL_RANK
2019-11-05T05:01:19.420768Z job-exec.info[0]: 300345720832: 3: stdout: Running exit $JOB_SHELL_RANK
2019-11-05T05:01:19.472671Z job-exec.info[0]: 300345720832: 0: stdout: Running exit $JOB_SHELL_RANK
2019-11-05T05:01:19.593160Z job-exec.info[0]: 300345720832: 1: stdout: Running exit $JOB_SHELL_RANK
2019-11-05T05:01:19.607128Z sched-simple.debug[0]: free: rank[0-3]/core0
```

If I run the test in isolation (i.e., make check TESTS=t2402-job-exec-dummy.t), it works as expected.

### LINKED ISSUE #2522: t1105-proxy.t fails with extra subscription messages
Another non-deterministic failure.  I believe the race here is that if the second `flux event sub -c1 hb` is slow to run, then the count of the `subscribe` logs is 2 rather than the expected 1.  I wonder if this could be tweaked to subscribe to an event like `foobar` that is then published via `flux event pub` as part of the test.  Kinda hard to ensure that the sub has been registered before sending the pub though.

test log: 

```
not ok 5 - flux-proxy manages event redistribution
FAIL: t1105-proxy.t 5 - flux-proxy manages event redistribution
#       
#               flux proxy $TEST_URI \
#                 "flux event sub -c1 hb& flux event sub -c1 hb& wait;wait" &&
#               FLUX_URI=$TEST_URI flux dmesg | sed -e "s/[^ ]* //" >event.out &&
#               test $(egrep "connector-local.*debug\[0\]: subscribe hb" event.out|wc -l) -eq 1 &&
#               test $(egrep "proxy.*debug\[0\]: subscribe hb" event.out|wc -l) -eq 1 &&
#               test $(egrep "connector-local.*debug\[0\]: unsubscribe hb" event.out|wc -l) -eq 1 &&
#               test $(egrep "proxy.*debug\[0\]: unsubscribe hb" event.out|wc -l) -eq 1
#       
ok 6 - flux-proxy permits dynamic service registration
```

event.out content in trash-directory:
```
broker.debug[0]: insmod connector-local
broker.info[0]: wireup: 4/4 (complete) 0.0s
broker.info[0]: Run level 1 starting
broker.debug[0]: insmod barrier
broker.debug[0]: insmod content-sqlite
broker.debug[0]: content backing store: enabled content-sqlite
broker.debug[0]: insmod kvs
broker.debug[0]: insmod kvs-watch
broker.debug[0]: insmod job-info
broker.debug[0]: insmod aggregator
broker.debug[0]: insmod cron
cron.info[0]: synchronizing cron tasks to event hb
aggregator.debug[0]: push: resource.hwloc.reload:0-14120: count=1 fwd_count=4 total=4
aggregator.debug[0]: push: resource.hwloc.reload:0-14120: count=3 fwd_count=4 total=4
aggregator.debug[0]: push: resource.hwloc.reload:0-14120: count=4 fwd_count=4 total=4
aggregator.debug[0]: sink: resource.hwloc.reload:0-14120: count=4 total=4
broker.debug[0]: insmod userdb
broker.debug[0]: insmod job-ingest
broker.debug[0]: insmod job-manager
job-manager.debug[0]: restart_from_kvs: added 0 jobs
broker.debug[0]: insmod job-exec
broker.debug[0]: insmod sched-simple
sched-simple.debug[0]: service_register
job-manager.debug[0]: scheduler: hello
job-manager.debug[0]: scheduler: ready single
sched-simple.debug[0]: ready: 32 of 32 cores: rank[0-3]/core[0-7]
broker.info[0]: rc1: running /home/sherbein/Repositories/flux-framework/flux-core/etc/rc1.d/01-enclosing-instance
broker.info[0]: Run level 1 Exited (rc=0) 12.3s
broker.info[0]: Run level 2 starting
broker.info[0]: runlevel 2 (300.0s) timer started
connector-local.debug[0]: subscribe hb
proxy.debug[0]: subscribe hb
connector-local.debug[0]: unsubscribe hb
proxy.debug[0]: unsubscribe hb
connector-local.debug[0]: subscribe hb
proxy.debug[0]: subscribe hb
connector-local.debug[0]: unsubscribe hb
proxy.debug[0]: unsubscribe hb
```

### PR DESCRIPTION
**Pull request by SteVwonder**
`t0004-event.t`, `t1105-proxy.t`, and `t2404-job-exec-dummy.t` were all failing when run under `make -j` and occasionally failing on Travis.

This PR prevents races by switching to `event-trace.lua`, reduce timeouts by increasing the timeout windows, and avoids tests interfering with one another by removing duplicate event names.

Closes #2522
Closes #2518 
Closes #2517

### CODE REVIEW

File: t/scripts/event-trace.lua [hunk 1]
```diff
@@ -84,5 +78,17 @@ local mh, err = f:msghandler {
 	end
     end
 }
+if err then
+   io.stderr:write("Error in registering exit event watcher\n")
+   os.exit(1)
+end
+if f:subscribe (s) < 0 then
```
Comment (grondo) [inline t/scripts/event-trace.lua]: I don't think the Lua `subscribe` method returns `< 0` on error. Lua idiom is to return `nil, error` on error, so the usual way to check for error is to do
```lua
local rc, err = f:subscribe (s)
if not rc then
    io.stderr:write ("subscribe: "..err)
end
```

another way to perform this check is to use the Lua `assert()` function
```lua
assert (f:subscribe (s))
```

which errors out with the second return value if the first return value is `nil` or `false`.

Comment (SteVwonder) [reply t/scripts/event-trace.lua]: Thanks! Good to know.

Updated.

**Comment by grondo** [comment]
Thanks for all the work to run down these racy tests! I've set merge-when-passing.

**Comment by SteVwonder** [comment]
> Thanks for all the work to run down these racy tests! I've set merge-when-passing.

No, thank you!  I mostly just nerd sniped you into doing the hard work.  

---

Restarting a failed builder.  Looks like Valgrind finished but still timed out 😕 

```
==12893== For counts of detected and suppressed errors, rerun with: -v

==12893== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

/usr/src/t/sharness.d/flux-sharness.sh: line 9: 12821 Alarm clock             perl -e 'use Time::HiRes qw( ualarm ) ; ualarm ((shift @ARGV) * 1000000) ; exec @ARGV or die "$!"' "$@"

not ok 1 - valgrind reports no new errors on 2 broker run
```
