### PR TITLE
job-manager: fix segfault when attempting to change priority of a running job

### LINKED ISSUE #3218: job-manager: segfault when changing priority of running job
Accidentally changed the priority of a running job, leading to a segfault.  This is on current master afc33964cc20c8ccff6fb33b829dc70096abc017

```
(gdb) bt
#0  0x00002aaaac426387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002aaaac427a78 in __GI_abort () at abort.c:90
#2  0x00002aaaac41f1a6 in __assert_fail_base (fmt=0x2aaaac57ace0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x2aaaab1b4e34 "handle", file=file@entry=0x2aaaab1bd6c4 "src/zlistx.c", line=line@entry=531, 
    function=function@entry=0x2aaaab1cc066 "zlistx_reorder") at assert.c:92
#3  0x00002aaaac41f252 in __GI___assert_fail (assertion=0x2aaaab1b4e34 "handle", file=0x2aaaab1bd6c4 "src/zlistx.c", line=531, 
    function=0x2aaaab1cc066 "zlistx_reorder") at assert.c:101
#4  0x00002aaaab17b7d0 in zlistx_reorder () from /lib64/libczmq.so.3
#5  0x00002aaabdbfbe06 in alloc_queue_reorder (alloc=<optimized out>, job=<optimized out>) at alloc.c:535
#6  0x00002aaabdbfcc63 in priority_handle_request (h=0x2aaad8001160, mh=<optimized out>, msg=0x2aaad800f890, arg=0x2aaabe033a00)
    at priority.c:103
#7  0x00002aaaaacecc24 in call_handler (mh=0x2aaad800c1f0, msg=msg@entry=0x2aaad800f890) at msg_handler.c:231
#8  0x00002aaaaaced359 in dispatch_message (type=1, msg=0x2aaad800f890, d=0x2aaad800acd0) at msg_handler.c:267
#9  handle_cb (r=0x2aaad800a4a0, hw=<optimized out>, revents=<optimized out>, arg=0x2aaad800acd0) at msg_handler.c:367
#10 0x00002aaaaad14525 in ev_invoke_pending (loop=0x2aaad800a4c0) at ev.c:3372
#11 0x00002aaaaad18077 in ev_run (loop=0x2aaad800a4c0, flags=0) at ev.c:3775
#12 0x00002aaaaacebdb3 in flux_reactor_run (r=r@entry=0x2aaad800a4a0, flags=flags@entry=0) at reactor.c:126
#13 0x00002aaabdbf6f19 in mod_main (h=0x2aaad8001160, argc=<optimized out>, argv=<optimized out>) at job-manager.c:136
#14 0x000000000040b48c in module_thread (arg=0x666da0) at module.c:214
#15 0x00002aaaab87aea5 in start_thread (arg=0x2aaabe034700) at pthread_create.c:307
#16 0x00002aaaac4ee8dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 

```

i suspect we need to do more than check the `alloc_pending` flag in the priority handler.

Edit: skimming code, looks like we need a `alloc_success` kind of flag.  Can't see an obvious way to tell alloc success has occurred.

### PR DESCRIPTION
**Pull request by chu11**
An attempt to fix #3218.  I hit a segfault when I accidentally tried to re-prioritize a running job (vs a pending job).

### CODE REVIEW

File: src/modules/job-manager/alloc.c [hunk 1]
```diff
@@ -240,6 +240,7 @@ static void alloc_response_cb (flux_t *h, flux_msg_handler_t *mh,
             if (event_job_post_pack (ctx->event, job, "alloc", NULL) < 0)
                 goto teardown;
         }
+        job->alloc_success = 1;
```
Comment (garlick) [inline src/modules/job-manager/alloc.c:243]: Can `job->has_resources` work here, instead of adding another flag?

Comment (chu11) [reply src/modules/job-manager/alloc.c:243]: ahh yes, its sent in `event_job_update()` so just didn't see it.

**Comment by chu11** [comment]
re-pushed using `has_resources` flag instead of a new `alloc_success` flag

**Comment by chu11** [comment]
hmmm `flux-sched` builder failed during the build with `flux-keygen: /usr/src/etc/flux: owner should be you`.  Retrying.

File: src/modules/job-manager/priority.c [hunk 2]
```diff
@@ -92,6 +92,11 @@ void priority_handle_request (flux_t *h,
         errno = EINVAL;
         goto error;
     }
+    if (job->has_resources) {
+        errstr = "job is alloced, priority cannot be changed";
```
Comment (garlick) [inline src/modules/job-manager/priority.c:96]: How about "priority cannot be changed once resources are allocated"?

**Comment by chu11** [comment]
re-pushed with the message tweak per @garlick comment above

File: t/t2210-job-manager-bugs.t [hunk 3]
```diff
@@ -60,5 +60,15 @@ test_expect_success 'issue3051: clean up' '
 	flux queue drain
 '
 
+#
+# Issue 3218 job-manager: segfault when changing priority of running job
+#
+
+test_expect_success 'issue3218: cannot reprioritize job with alloc success' '
```
Comment (garlick) [inline t/t2210-job-manager-bugs.t:67]: apologies for not noticing earlier, but the commit description needs some editing:

> Add test ensuring segfault from attempt to re-prioritize a running job does not lead to a segfault.

Maybe go with

> Add test ensuring job manager does not segfault when a priority change is requested on a running job.

While you're changing it, the commit title should probably not just reference an issue number and the test output could say something a little more descriptive.  Maybe go with
> issue3218: priority change on running job doesn't segfault

**Review by garlick — APPROVED** [review]
Marking approved but I think the test commit could use one more pass.
(I'm fine with MWP after that).

Thanks for fixing this!

**Comment by chu11** [comment]
@garlick thanks.  Re-pushed with a couple of tweaks.  Commit message is now:

```
    testsuite: Add job priority change segfault test
    
    Add test ensuring job manager does not segfault when a priority change
    is requested on a running job (issue #3218).
```

and the test title is now

```
-test_expect_success 'issue3218: cannot reprioritize job with alloc success' '
+test_expect_success 'issue3218: priority change on running job doesnt segfault' '
```

**Comment by garlick** [comment]
I went ahead and set MWP - hope that's OK.

**Comment by chu11** [comment]
@garlick awesome, thanks!  (I now see that you thumbed up my other comment, which I should have taken for "changes are good", oops).
