### PR TITLE
kvs: Fix duplicate append corner case

### LINKED ISSUE #2545: lt-flux-broker: src/zlistx.c:360: zlistx_detach: Assertion `self->size == 0' failed
In #2540, @grondo hit a random assert while playing with my branch.  I was able to eventually reproduce regularly on master 2e299e27d2520b74e104615618cf551a3c6ec3ce using this script

```
#!/bin/sh

for i in `seq 1 10`
do
   echo "**** $i"
   src/cmd/flux start --size=8 stats.sh
done
```

Where stats.sh is

```
rm -f *.json
flux mini run -n1 --dry-run hostname >job.json
flux mini run -N1 --dry-run t/ingest/submitbench -r 1024 job.json > submitjob.json
t/ingest/submitbench -r 8 submitjob.json
sleep 40
```

the sleep 40 is b/c in the master branch the `flux job stats` command does not yet exist.  We have to wait until all jobs are submitted for the reproducer to reproduce more reliably, and 40 seconds is just about right for running on opal.  With the above scripts, I hit the issue 7/10 times on opal.

The assert leads to the following backtrace.

```
#0  0x00002aaaac224377 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install czmq-3.0.2-3.el7.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.1chaos.ch6.x86_64 libcom_err-1.42.9-16.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libsodium-1.0.18-1.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 lz4-1.7.5-3.el7.x86_64 openpgm-5.2.122-2.el7.x86_64 pcre-8.32-17.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 zeromq-4.1.5-3.ch6.x86_64
(gdb) bt
#0  0x00002aaaac224377 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002aaaac225a68 in __GI_abort () at abort.c:90
#2  0x00002aaaac21d196 in __assert_fail_base (fmt=0x2aaaac378c20 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x2aaaab1c06e9 "self->size == 0", 
    file=file@entry=0x2aaaab1c06c4 "src/zlistx.c", line=line@entry=360, function=function@entry=0x2aaaab1cf0d0 "zlistx_detach") at assert.c:92
#3  0x00002aaaac21d242 in __GI___assert_fail (assertion=0x2aaaab1c06e9 "self->size == 0", file=0x2aaaab1c06c4 "src/zlistx.c", line=360, function=0x2aaaab1cf0d0 "zlistx_detach") at assert.c:101
#4  0x00002aaaab17e192 in zlistx_detach () from /lib64/libczmq.so.3
#5  0x00002aaaab17e1e2 in zlistx_delete () from /lib64/libczmq.so.3
#6  0x00002aaaab17e3fa in zlistx_purge () from /lib64/libczmq.so.3
#7  0x00002aaaab17e44e in zlistx_destroy () from /lib64/libczmq.so.3
#8  0x00002aaac4ad5461 in job_state_destroy (data=0x2aaad000b140) at job_state.c:158
#9  0x00002aaac4ad44ee in info_ctx_destroy (ctx=0x2aaad000c1a0) at job-info.c:143
#10 0x00002aaac4ad45ad in mod_main (h=<optimized out>, argc=<optimized out>, argv=<optimized out>) at job-info.c:186
#11 0x000000000040a5b6 in module_thread (arg=0x65faf0) at module.c:162
#12 0x00002aaaab678ea5 in start_thread (arg=0x2aaac4f12700) at pthread_create.c:307
#13 0x00002aaaac2ec8cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #2547, fix corner case in which append could be duplicated.  Solution was to cache the root directory used to make the root cpy.  If a stall + replay occurs, replay on a brand new root cpy that has been refreshed via `json_deep_copy()`.

Added unit test.  Confirmed unit test failed on master, but works after fix.

Also fixed #2545 (which found this issue) in this PR, since it's trivial once the core issue was fixed.

### CODE REVIEW

**Comment by chu11** [comment]
> Is it still true that once a commit stalls, no other commit can start until that one un-stalls and completes?

True

> Before, only the commit request was kept as "state" when the commit stalled, so the restart was completely from scratch. Now we're storing some state including the partially modified root object?  

Yes, although it's sort of unnecessary b/c (as you noticed) we're running through the entire transaction array again.

> Is there a reason we are not storing the position within the ops array so we could restart at the operation that stalled and thus avoid repeating work and fix this bug as a side effect?

Yes.  The subtletly (and perhaps I should add an example/comment in the code) is that we return all missing references in the transaction array, not just 1 reference.

Lets take the following transaction array:

```
put a=1
put DIR0.a=1
append b=1
put DIR1.a=1
```

lets say that the reference for `DIR0` and `DIR1` leads to missing references.  So we stall and return both those references to the caller.

We cannot store the index of the `append`, b/c we need `DIR0.a=1` to be replayed.  But if we replay from `DIR0.a=1`, we'd replay `append b=1` and that'd be a duplicate append.

I think the only safe thing to do is wipe the rootcpy so it can start over.

**Comment by garlick** [comment]
OK, thanks for that.  Very helpful!

I assume we're counting appends and not _unconditionally_ starting over because the cost of the deep root copy is non-negligible?  (It's not a full root copy as I recall, just the parts that are touched by the commit?)

Can we use the append count to simply skip over that number of appends on the restart instead of throwing away the object?

**Comment by chu11** [comment]
> I assume we're counting appends and not unconditionally starting over because the cost of the deep root copy is non-negligible? (It's not a full root copy as I recall, just the parts that are touched by the commit?)

Mostly I'm counting appends b/c I don't want to do a `json_deep_copy()` on every stall/replay.  Only on ones in which appends occur.  Perhaps a "did I do an append" flag would be more appropriate/less confusing?

You're correct, it's not a full root copy.

> Can we use the append count to simply skip over that number of appends on the restart instead of throwing away the object?

That would lead to operations being done out of order, which isn't safe.   I'm trying to think of an example.  How about:

```
put DIR.a=1
unlink DIR
append DIR=1
```

`DIR` is a missing reference which will cause a stall + replay.  But unbeknownst to the KVS, the `DIR` reference is later deleted and replaced.  If we let the unlink + append occur in the root cpy, not clear the root cpy, then perform DIR.a=1 in the replay, skip the append in the replay, the result would be different/incorrect.

**Comment by garlick** [comment]
Got it.  Thanks for patiently answering my questions!  OK, your approach sounds like the right one then.  I'll give the code a review in a bit.

File: src/modules/kvs/test/kvstxn.c [hunk 1]
```diff
@@ -3079,6 +3079,132 @@ void kvstxn_process_append_errors (void)
     json_decref (root);
 }
 
+/* Issue #2547 - if a missing ref causes a stall & replay, it's
+ * possible an append could be duplicated twice.  Test ensures
```
Comment (garlick) [inline src/modules/kvs/test/kvstxn.c]: Did you mean it's possible an append could be "applied" twice?

File: src/modules/kvs/kvstxn.c [hunk 2]
```diff
@@ -76,6 +78,8 @@ static void kvstxn_destroy (kvstxn_t *kt)
         json_decref (kt->keys);
         json_decref (kt->names);
         json_decref (kt->rootcpy);
+        if (kt->entry)
```
Comment (garlick) [inline src/modules/kvs/kvstxn.c]: cache_entry_decref() is a no-op if entry=NULL so extra check is not needed here.

File: src/modules/kvs/kvstxn.c [hunk 3]
```diff
@@ -431,7 +435,7 @@ static int kvstxn_val_data_to_cache (kvstxn_t *kt, int current_epoch,
 }
 
 static int kvstxn_append (kvstxn_t *kt, int current_epoch, json_t *dirent,
-                          json_t *dir, const char *final_name)
+                          json_t *dir, const char *final_name, int *append_count)
```
Comment (garlick) [inline src/modules/kvs/kvstxn.c]: I think your idea of changing this to a flag/boolean is probably a good one that would make its purpose more clear.

**Comment by chu11** [comment]
rebased and made adjustments per @garlick comments above

**Comment by garlick** [comment]
Thanks, LGTM!
