### PR TITLE
history: track root jobs

### LINKED ISSUE #5475: jobtap history plugin throws errors
In one of @vsoch's cloudy experiments, in  the output of a failing intel MPI job, we noticed two jobtap errors:

```
jobtap: job.new: callback returned error
jobtap: job.inactive.add: callback returned error
```

The only jobtap in-tree that registers `job.inactive-add` is `history`.  Maybe there is something to run down here or at least a couple places where log messages could be added to give us something to go on next time.

### PR DESCRIPTION
**Pull request by garlick**
Problem: the job history plugin uses an integer userid as hash key, but the hash implementation won't accept a key (NULL) for userid 0.  This results in errors like:
```
jobtap: job.new: callback returned error
jobtap: job.inactive.add: callback returned error
```
    
Map userid 0 to `(uid_t)-1` since that value is reserved in POSIX.
    
Fixes #5475

### CODE REVIEW

File: src/modules/job-manager/plugins/history.c [hunk 1]
```diff
@@ -124,6 +142,7 @@ static int jobtap_cb (flux_plugin_t *p,
     struct history *hist = arg;
     struct job_entry *entry;
     int userid;
+    const char *key;
```
Comment (grondo) [inline src/modules/job-manager/plugins/history.c:145]: should this be `const void *`?

**Review by grondo — APPROVED** [review]
LGTM! Just one question inline.

**Comment by garlick** [comment]
I'll go ahead and set MWP here.
