### PR TITLE
ci: add el10 build, fix testenv workflow bugs, and enable automated image builds

### LINKED ISSUE #7509: Flux el10 Container Request
Hello Flux Team,

I am writing to request el10 containers both for amd64 and arm64. The Flux containers are beloved and very useful to us. The arm64 containers are also generally compatible with Apple Silicon, which allows us to redistribute a proof-of-concept environment to a variety of partners for testing basic benchmarking, MPI task affinity, and other HPC software stacks' Flux interoperability.

Thanks,
Nate

### PR DESCRIPTION
**Pull request by grondo**
This PR ostensibly adds a new `el10` build to CI. However, to ease the deployment of the resulting base `fluxrm/testenv:el10` image, there's also an attempt to resolve some outstanding issues in the `testenv.yml` workflow:

- Add bookworm 32bit build and test support
- Remove some dead code probably cut and paste from `main.yml`
- Add el10 to the list of supported distros for workflow dispatch
- Support rebuilding images _locally_ with `docker-run-checks.sh` when a Dockerfile has been modified or the testenv image is unavailable. This is now what happens in PRs that modify any Dockerfile by default
- Automate testenv rebuilds when any Dockerfile is modified in a push to master
- Remove all stale distros under `src/test/docker/*`
- Rewrite `src/test/docker/README.md` to reflect the new workflow

Fixes #7509

### CODE REVIEW

**Comment by grondo** [comment]
Part of the experiment of this PR is to see if the addition of el10 (and modified bookworm Dockerfile) result in local builds of the requisite images. Then if we merge this to master, that will hopefully automatically trigger the build of the `fluxrm/testenv:el10` image and rebuild of `fluxrm/testenv:bookworm` (with all the right architectures in the manifest)

Thanks to @wihobbs for getting this started!

**Comment by grondo** [comment]
Looks like the local build of a modified image worked:

> Building testenv image el10 locally (Dockerfile modified in this branch)

**Review by garlick — APPROVED** [review]
Nice improvement!

File: src/test/docker/docker-run-checks.sh [hunk 1]
```diff
@@ -140,6 +140,38 @@ CONFIGURE_ARGS="$@"
...
+        BUILD_TESTENV_REASON="Dockerfile modified in this branch"
+    fi
+    if [[ -z "$BUILD_TESTENV_REASON" ]]; then
+        docker pull "${BASE_DOCKER_REPO}:${IMAGE}" >/dev/null 2>&1 \
+            || BUILD_TESTENV_REASON="image not found on DockerHub"
+    fi
+    if [[ -n "$BUILD_TESTENV_REASON" ]]; then
+        checks_group_start \
+            "Building testenv image ${IMAGE} locally (${BUILD_TESTENV_REASON})"
+        docker build \
```
Comment (wihobbs) [inline src/test/docker/docker-run-checks.sh:170]: I'm a little confused on why this is necessary for the github action. The `build-<arch>-distro` builds the images, and then they're loaded by `docker load -i`, which _should_ pick them up as `fluxrm/testenv:distro-arch` without fetching, because the image is already available locally. 

Since this provides a way to force the script build locally I can see it being handy locally for testing, so it's a good addition, I'm just curious what you ran into that I hadn't.

File: .github/workflows/testenv.yml [hunk 2]
```diff
@@ -1,4 +1,9 @@
 on:
+  push:
+    branches:
+      - master
+    paths:
+      - 'src/test/docker/*/Dockerfile'
```
Comment (wihobbs) [inline .github/workflows/testenv.yml]: Will this automatically trigger a rebuild if we edit a _script_ in a `src/test/docker/<distro>` directory? 

Is it worth making this
```suggestion
      - 'src/test/docker/*/*'
```
so that _any_ changes in a distro's directory trigger a rebuild, not just Dockerfiles?

My motivating question is that the original trouble we had with the images timing out in CI IIRC was due to #6907.

**Review by wihobbs — APPROVED** [review]
Thanks for cleaning up my janky original PR! I just had a few questions inline. 

I like that the script preserves the option of triggering a manual rebuild. I was going to suggest now we might not need [`77f3fed`](https://github.com/flux-framework/flux-core/commit/77f3fed369fe2e820eb98846a72a0409cf187868) but perhaps we can leave it since the manual option is still there.

File: src/test/docker/docker-run-checks.sh (hunk 1 above)
Comment (grondo) [reply src/test/docker/docker-run-checks.sh:170]: This change allows a developer to push up a PR and have it build a new or modified image before that image is deployed to `fluxrm/testenv` (like here for `el10`). Thus the PR ci process doesn't have to depend on the `testenv.yml` workflow. Once the PR is approved and is merged to master, then the official `testenv` build happens.

File: .github/workflows/testenv.yml (hunk 2 above)
Comment (grondo) [reply .github/workflows/testenv.yml]: That makes sense. I will note however that this wouldn't have helped with #6907 since that change was in `./scripts` not under `src/test/docker`. In those cases we can trigger a manual build. The only other things in `src/test/docker/*/*` for rebuildable images are `config.site`.

File: src/test/docker/docker-run-checks.sh (hunk 1 above)
Comment (wihobbs) [reply src/test/docker/docker-run-checks.sh:170]: Oh, I see. The PR CI process isn't using `testenv.yml` at all, that just happens on a manual trigger or merge to master -- got it.

File: .github/workflows/testenv.yml (hunk 2 above)
Comment (wihobbs) [reply .github/workflows/testenv.yml]: Yeah, I was thinking about that. I don't have a good solution :-(

Comment (grondo) [reply .github/workflows/testenv.yml]: Ok fixed to also rebuild if the `config.site` are updated.

For `./scripts/*` used in Dockerfiles, there's only a few of them. We could add to the testenv `paths` and modify the logic that derives which images to rebuild accordingly. I'll look into that.

Comment (grondo) [reply .github/workflows/testenv.yml]: Ok! Pushed a new commit on top that adds detection of which images need to be rebuilt when there's a change in a file under `./scripts/*`. Same detection used in `docker-run-checks.sh`.

Comment (wihobbs) [reply .github/workflows/testenv.yml]: Oh nice!

**Comment by grondo** [comment]
Once tests pass I _think_ someone will need to hit the merge button since `.github` was touched here. Then we'll have the real test: to see if the `el10` image auto-builds via the `testenv` workflow on merge.
