### PR TITLE
t/kvs/watch_disconnect: Fix racy behavior

### LINKED ISSUE #2015: not ok 2 - multi-node kvs watcher gets disconnected on client exit
After merge of #2011, the [travis-ci check of master](https://travis-ci.org/flux-framework/flux-core/builds/493359896) failed the same test in 3 different builders:

```
not ok 2 - multi-node kvs watcher gets disconnected on client exit
FAIL: t1103-apidisconnect.t 2 - multi-node kvs watcher gets disconnected on client exit
#	
#		${FLUX_BUILD_DIR}/t/kvs/watch_disconnect
#	
# failed 1 among 2 test(s)
1..2
ERROR: t1103-apidisconnect.t - exited with status 1
```

```
Found ./t/t1103-apidisconnect.output
expecting success: 
	before_watchers=`flux module stats --parse "watchers" kvs-watch` &&
	echo "waiters before test: $before_watchers" &&
	test_expect_code 142 run_timeout 1 flux kvs get --watch --waitcreate noexist &&
	check_kvs_watchers $before_watchers 3
waiters before test: 0
Alarm clock
Try 1: 0
ok 1 - kvs watcher gets disconnected on client exit
kvs watcher gets disconnected on client exit
expecting success: 
	${FLUX_BUILD_DIR}/t/kvs/watch_disconnect
watch_disconnect: test watchers: 4
watch_disconnect: disconnected
watch_disconnect: test watchers: 1
watch_disconnect: Test failure, watchers were not removed on disconnect: Success
not ok 2 - multi-node kvs watcher gets disconnected on client exit
# failed 1 among 2 test(s)
1..2
```

### PR DESCRIPTION
**Pull request by chu11**
Add several loops / waits to wait for rpcs / disconnects to be
processed, to hopefully avoid several racy scenarios.

Fixes #2015

### CODE REVIEW

**Comment by chu11** [comment]
hit a #1025, but otherwise fix seems to work.  I am going to restart all builders a few times to make sure it's really fixed.

File: t/kvs/watch_disconnect.c [hunk 1]
```diff
@@ -66,15 +82,31 @@ int main (int argc, char **argv)
         log_err_exit ("flux_open");
     w0 = count_watchers (h);
     send_watch_requests (h, "nonexist");
-    w1 = count_watchers (h) - w0;
+
+    /* must spin / wait for watchers to be registered */
+    for (i = 0; i < MAX_ITERS; i++) {
+        w1 = count_watchers (h) - w0;
+        if (w1 == rankcount)
```
Comment (grondo) [inline t/kvs/watch_disconnect.c]: could the test use a barrier here instead of looping and sleeping? I guess if the `sleep (1)` is only rarely invoked it isn't too big a deal...

Comment (chu11) [reply t/kvs/watch_disconnect.c]: the test was passing all the time in the past, so hopefully the sleeps are rare :-)

Not sure a barrier will be doable.  Basically, they are spins to ensure that RPCs have been sent / received / processed b/c in both cases an RPC response isn't coming back.  Perhaps should use ```usleep()``` instead?

Comment (grondo) [reply t/kvs/watch_disconnect.c]: If the sleep is rare then it isn't too big of a deal.

Comment (chu11) [reply t/kvs/watch_disconnect.c]: I sleep "0.1" seconds in various kvs tests, so I'll just continue the trend and convert to usleep in 0.1 second chunks.

**Comment by chu11** [comment]
re-pushed using ```usleep()``` instead of ```sleep()```.  I restarted the builder 3 times and never hit the race, so I think if travis passes this time (4th overall) we can declare the race fixed.

**Comment by grondo** [comment]
Thanks!

**Comment by grondo** [comment]
Ok, this is ready to merge then? :+1:

**Comment by chu11** [comment]
yup, I think it's good to go
