### PR TITLE
kvs: correct code logic about what is an append

### LINKED ISSUE #6207: throughput.py test: incorrect number of tests submitted in status
I've noticed this a few times, where the number of jobs submitted does not match the number of jobs requested.

```
 32768 jobs:  33478 submitted,      0 running, 32768 completed                                                                              
number of jobs: 32768                                                                                                                       
submit time:    18.076s (1812.8 job/s)                                                                                                      
script runtime: 511.485s                                                                                                                    
job runtime:    511.244s                                                                                                                    
throughput:     64.1 job/s (script:  64.1 job/s)                                                                                            
total 708M                                     
```

the test appears to still run the correct number of tests, but the "submitted" number is incorrect.  I noticed one at around 39K as well.

### PR DESCRIPTION
**Pull request by chu11**
Problem: In PR #2547, a fix was added into the KVS to deal with duplicate appends to a KVS entry.  However, a corner case was left in the code. When an append is done to a KVS entry that does not exist, the append is treated like a normal insertion.  This corner case should also be counted as an "append".  Otherwise, duplicate appends could happen at the beginning of a KVS entry when it is created.

Solution: Set the append flag to true when a KVS entry does not exist and the append is treated like an insert.

Fixes #6207

----

Side note, now that all "good paths" are counted as appends, I could moved  `(*append) = true` into the end of the function before `return 0`.  But given how the error handling is done in the function, I felt leaving each of the `(*append) = true` near their "we did an append" I thought was better.  But that's just me.  Could be overridden by review votes :-)

### CODE REVIEW

File: src/modules/kvs/kvstxn.c [hunk 1]
```diff
@@ -495,6 +495,7 @@ static int kvstxn_append (kvstxn_t *kt, json_t *dirent,
         /* entry not found, treat like normal insertion */
         if (treeobj_insert_entry (dir, final_name, dirent) < 0)
             return -1;
+        (*append) = true;
```
Comment (grondo) [inline src/modules/kvs/kvstxn.c:498]: Not knowing this code well (or at all), a comment here as to why `*append = true` would be helpful, especially given the comment just above (`treat like normal insertion`).

**Review by grondo — APPROVED** [review]
Nice! LGTM! just one suggestion of an additional comment in the code.

I also verified I can no longer reproduce the issue with this fix. Thanks!

**Comment by chu11** [comment]
thanks!  re-pushed with an extra comment.  will set MWP.
