### PR TITLE
resource: fail get-xml request on quorum subset

### LINKED ISSUE #3884: consider failing `resource.get-xml` if broker quorum is a subset of the instance
This was brought up as an idea in flux-framework/flux-sched#866, where a system instance's configured R was missing JGF augmentation, and the system deadlocked, blocked on this RPC.  A proposed solution is to fail the RPC with a nice human readable error message if the `broker.quorum` is set to a subset of the instance, since that could mean that we need to  begin operations with some nodes down, and the `get-xml` RPC could block indefinitely.

### PR DESCRIPTION
**Pull request by garlick**
Problem: if R is missing augmented graph information, fluxion
might block forever on resource.get-xml request for resource
discovery results.

Resource discovery is the natural fallback if resources not
not configured.  But fluxion cannot tell the difference between
R that lacks configured JGF augmentation because it was misconfigured,
and R allocated by a scheduler that doesn't support it.

If discovered hwloc results are not immediately available at the time
of the request, fail the request if the broker.quorum attribute is
less than the full instance, as this indicates that the instance
should begin operation with some ranks offline, and R should contain
all needed information.

Tack a test onto t3301-system-latestart.t

Fixes #3884.

### CODE REVIEW

**Comment by garlick** [comment]
This does feel a bit hacky.

I might be forgetting the details, but wasn't the hwloc access implemented because the "Rv1 reader" code had not yet been developed in fluxion?  Could this hack, and `get-hwloc` RPC for that matter, be avoided by falling back the Rv1 reader if the JGF was not inserted into R?

It might be better to unwind some hacks rather than add more :-)

File: src/modules/resource/inventory.c [hunk 1]
```diff
@@ -470,6 +470,24 @@ static int get_from_kvs (struct inventory *inv, const char *key)
...
+{
+    const char *quorum;
+    uint32_t size;
+    char buf[32] = "0";
+
+    if (!(quorum = flux_attr_get (h, "broker.quorum"))
+        || flux_get_size (h, &size) < 0)
+        return false;
+    if (size > 1)
+        snprintf (buf, sizeof (buf), "0-%d", (int)size - 1);
```
Comment (dongahn) [inline src/modules/resource/inventory.c:485]: Super minor nit: check the return code for an error?

File: src/modules/resource/inventory.c [hunk 2]
```diff
@@ -470,6 +470,24 @@ static int get_from_kvs (struct inventory *inv, const char *key)
...
+    if (strcmp (buf, quorum) == 0)
```
Comment (dongahn) [inline src/modules/resource/inventory.c:486]: If a very unlikely failure from `snprintf` above, `buf` may not be well-formed and buffer overflow could happen? `strncmp` since this is a known buffer size?

File: src/modules/resource/inventory.c [hunk 3]
```diff
@@ -489,7 +507,17 @@ static void resource_get_xml (flux_t *h,
         errstr = "this RPC only works on rank 0";
         goto error;
     }
+    /* xml is still being collected.  If broker.quorum is not the entire
+     * instance, then this may never complete, so fail the request in that
+     * case; otherwise save the request in inv->waiters for later response.
+     */
     if (!inv->xml) {
+        if (quorum_subset (h)) {
+            errno = EINVAL;
```
Comment (dongahn) [inline src/modules/resource/inventory.c:516]: `EWOULDBLOCK` or `EAGAIN`? Since it is not like the RPC argument was invalid but the state of the flux instance cannot service the RPC?

**Review by dongahn — APPROVED** [review]
LGTM. Just minor nits.

**Comment by dongahn** [comment]
>  might be forgetting the details, but wasn't the hwloc access implemented because the "Rv1 reader" code had not yet been developed in fluxion?

Yap. 

The Rv1 reader code is currently python as part of `flux ion-R`. But no C++ code yet. My biggest fear going down on the path of integrating on-the-fly `rv1 reader` into fluxion is that `.scheduling` key will soon need to contain much more information than what `rv1` currently contains (e.g., Rabbit multitiered storage info) and extending the `rv1 reader` feature for future use will be pretty brittle and seems a bit like a premature optimization. 

Having this seems like a minimum viable for now, we then perfect it when more use cases come to our ways in the future?

File: src/modules/resource/inventory.c (hunk 2 above)
Comment (garlick) [reply src/modules/resource/inventory.c:486]: `snprintf()` does ensure the string is terminated even on overflow so that should not be required.

File: src/modules/resource/inventory.c (hunk 3 above)
Comment (garlick) [reply src/modules/resource/inventory.c:516]: Given that we're returning a textual error, all we really need for errno is _something_ nonzero.  The intent was that fluxion would detect the error and log the human readable string at LOG_ERR level to leave a big clue for someone.  It shouldn't need to do anything with the errno value.

File: src/modules/resource/inventory.c (hunk 1 above)
Comment (garlick) [reply src/modules/resource/inventory.c:485]: Its not really possible to overflow the buffer unless there were a programming error here, but maybe this function ought to have a chance to fail instead of just returning the logical results.  Let me fix that.

File: src/modules/resource/inventory.c (hunk 2 above)
Comment (dongahn) [reply src/modules/resource/inventory.c:486]: Nice to know. thx

File: src/modules/resource/inventory.c (hunk 3 above)
Comment (dongahn) [reply src/modules/resource/inventory.c:516]: Fluxion use case is fine. Just caught my eyes in case this RPC used by something other than fluxion in the future. Ok as is.

File: src/modules/resource/inventory.c (hunk 1 above)
Comment (dongahn) [reply src/modules/resource/inventory.c]: I don't even know if I actually check the return code. But I thought I would mention in case you folks do that in `flux-core`. BTW, you do also guard some of the low level system functions from returning prematurely when being attached to a debugger?

**Comment by garlick** [comment]
> My biggest fear going down on the path of integrating on-the-fly rv1 reader into fluxion is that .scheduling key will soon need to contain much more information than what rv1 currently contains (e.g., Rabbit multitiered storage info) and extending the rv1 reader feature for future use will be pretty brittle and seems a bit like a premature optimization.

I'm not sure I get why it would be brittle.  Rv1 is [well defined](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_20.html) and incorporated into the design of several components.  It shouldn't change at this point without becoming Rv2, which I think would be a different reader?

It's our only standardized abstract resource definition at this point, it handles the majority of our production systems, and it's compact and simple to parse if you have jansson, idset, and hostlist libraries avaialble.    My vote would be we go ahead and implement it.  If we did, then we would not require the extra sys admin step of augmenting R on most systems - extra steps for exotic systems only :-)

But sure we have lots of things on our plate and we have to prioritize.

**Comment by dongahn** [comment]
> I'm not sure I get why it would be brittle. Rv1 is well defined and incorporated into the design of several components. It shouldn't change at this point without becoming Rv2, which I think would be a different reader?

Good point. Brittle was a bad choice of word. Maybe "agile" might have been a better choice...

When we start to test an exotic system like El Cap testbed in a few months, we will soon need a way to inject resources that are not defined by `RV1` but still develop and test things pretty quickly. An ability to inject that as an JGF into the initial R can help with this. Yes, it is true we can define Rv2 to cover those resources which we will at some point. My observation from the past has been it could take significant amounts of time to define it formally. 

Having said that, I can see us implementing on-the-fly RV1 reader and use it only when `.scheduling` key isn't defined.

**Comment by garlick** [comment]
> When we start to test an exotic system like El Cap testbed in a few months, we will soon need a way to inject resources that are not defined by RV1 but still develop and test things pretty quickly. An ability to inject that as an JGF into the initial R can help with this. Yes, it is true we can define Rv2 to cover those resources which we will at some point. My observation from the past has been it could take significant amounts of time to define it formally.

I think inserting JGF in Rv1 under the opaque scheduling key is a fine stopgap for exotic systems until we have time to work on Rv2, which might be a while.  IMHO the Rv1 reader is desirable in addition to that, to keep on track with the overall design. 

There may be a startup performance benefit at scale too, because we are only gathering the bulky hwloc XML in order to support  the `get-xml` RPC for fluxion.  The "resource discovery" algo in the resource module is to gather/reduce Rv1 fragments which are much more compact than the hwloc XML.  The XML was  tacked on so that fluxion wouldn't need to implement the Rv1 reader right away.  A lot of data is being moved unnecessarily during instance bootstrap as a result.

**Review by grondo — APPROVED** [review]
This seems like a good stopgap for now to me.

**Comment by dongahn** [comment]
@garlick: all good points and I agree. Let's plan this and using rv1 reader when we don't have `.scheduling` key seems like a good compromise. For immediate fluke testing, we should probably plan to land this PR?

**Comment by garlick** [comment]
I'll go ahead and set MWP - thanks for the review and discussion!
