### PR TITLE
libjob: add flux_job_result(3)

### LINKED ISSUE #3575: Idea: new wait/returncode functionality
Since `flux.job.wait` is restricted to the instance owner (for good reason from what I've heard), it seems like some new kind of `wait` functionality that is available universally would be a good addition. 

To avoid confusion with the existing `wait` function, I think it could be called `returncode`. And, like the name implies, it would return the return code of the job. Also, it wouldn't support wait-any functionality, although maybe that could be added later if it was useful. I'm just guessing that wait-any is primarily useful **a)** as an optimization or **b)** if you yourself are submitting _all_ the jobs, in which case you're probably the instance owner and could just use `wait`.

Here is a seriously flawed pass at such a function in Python, as a wrapper around `event_watch_async`:

```python

import concurrent.futures as cf
import os

import flux.job


def _returncode_callback(flux_future, user_future):
    """Invoked when a new event is ready for a job.

    If the event is 'finish' or 'exception', fulfill the user-facing future.
    """
    event = flux_future.get_event()
    if event.name == "finish":
        exit_status = event.context["status"]
        if os.WIFEXITED(exit_status):
            user_future.set_result(os.WEXITSTATUS(exit_status))
        elif os.WIFSIGNALED(exit_status):
            user_future.set_result(-os.WTERMSIG(exit_status))
        else:
            user_future.set_exception(ValueError(exit_status))
    elif event.name == "exception" and event.context["severity"] == 0:
        user_future.set_exception(flux.job.JobException(event))


def returncode_async(handle, jobid):
    """Get the returncode for a given job asynchronously.

    Returns a future representing the returncode of the job. If the job hits
    an exception (such that the job never completes) a `JobException` is set on the
    future.

    :param handle: a `flux.Flux()` handle.
    :param jobid: Flux jobid of the job to check
    """
    user_future = cf.Future()
    flux.job.event_watch_async(handle, jobid).then(_returncode_callback, user_future)
    return user_future
```

What I have is really bad because **a)** it returns a different kind of future than most of the `flux.job` functions and **b)** if you wait on the future it won't actually fulfill. To make it work properly I think I would need to be able to manually create and fulfill Flux futures, which I don't know how to do.

Of course, this proposed `returncode` function is something that users could implement themselves, but I think it might save them some hassle.

### PR DESCRIPTION
**Pull request by grondo**
This is an offshoot of an idea proposed by @jameshcorbett in #3575.

The code for `flux job status` is abstracted into a new API function: `flux_job_wait_status(3)`. This function returns a future that is fulfilled when the job eventlog reaches the end condition, and the future result contains some convenient information for getting a processed exit code, detecting if the job started or hit an exception, etc.

`flux job status` is then switched to this new interface.

Not too happy about the name of the function nor the requirement for a new structure added to the interface, but this is just an early demonstration for now.

A next step would be to develop a Python binding using this interface that meets @jameshcorbett's use case.

Fixes #3575

### CODE REVIEW

**Comment by grondo** [comment]
It occurred to me that what we really want here is a function to wait for the "result" of any job, so I've changed the name of the function in the C API to `flux_job_result(3)`. This function returns a `flux_future_t` which is fulfilled with a `struct flux_job_result` structure when the job result is available. Currently the structure looks like this:

```C
struct flux_job_result {
    flux_jobid_t id;
    flux_job_result_t result;
    bool started;
    int status;
    int exitcode;
    bool exception;
    int exception_severity;
    char *exception_type;
    char *exception_note;
};
```

It feels wrong to expose a structure like this in the API since we have yet to do anything like that. If the _idea_ of `flux_job_result(3)` is acceptable, then perhaps what to do would be to store the data currently represented in `struct flux_job_result` in a `json_t *` inside the future, and make the individual members accessible via `flux_job_result_unpack(3)` style accessor. Would that be any more palatable?

Anyway, this WIP PR now has a Python binding for `flux_job_result(3)`, `flux.job.result_async()`.

demo:

```python
#!/usr/bin/env python3

import sys
import time
import json
import argparse
import flux
from flux.job import JobspecV1

h = flux.Flux()

jobspec = JobspecV1.from_command(sys.argv[1:])

jobid = flux.job.submit(h, jobspec)

result = flux.job.result_async(h, jobid).get_result()

print (result)
```

```console
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py hostname
Exit 0
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py false
Exit 1
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py foo
Exit 127 (Exception: type=exec note="task 0: start failed: foo: No such file or directory")
```

**Comment by garlick** [comment]
> make the individual members accessible via flux_job_result_unpack(3) style accessor. Would that be any more palatable?

That sounds much better to me than exposing the struct.

**Comment by garlick** [comment]
I wonder if it would be useful to add a `flags` parameter to `flux_job_result()` to indicate how much detail is required?  It might be possible to consolidate `flux_job_wait()` with this interface, or add other detail like stdio down the road.  (Or maybe instead of integer mask of enum flags, a `json_t` array of key names would work better for bindings?)

**Comment by grondo** [comment]
Ok, I've changed the interface to use a stored `json_t *` for the job "result" information.

The C API now looks like:
```c
/*  Wait for job to reach its terminal state and fetch the job result
 *   along with other ancillary information from the job eventlog.
 */
flux_future_t *flux_job_result (flux_t *h, flux_jobid_t id);

/*  Get the job result "payload" as a JSON string
 */
int flux_job_result_get (flux_future_t *f,
                         const char **json_str);

/*  Decode and unpack the result payload from future `f`.
 *  The result object contains the following information:
 *
 *   {
 *     "id":i,                 jobid
 *     "result:i,              flux_job_result_t
 *     "started":i,            1 if job had a 'start' event, 0 otherwise
 *     "status":i,             wait status if job started
 *     "exitcode":i,           decoded exit code if job started
 *     "exception":i,          1 if job had an exception, 0 otherwise
 *     "exception_severity"?i, exception severity (if exception)
 *     "exception_type"?s,     exception type (if exception)
 *     "exception_note"?s      exception note (if exception)
 *   }
 *
 */
int flux_job_result_get_unpack (flux_future_t *f, const char *fmt, ...);
```

The Python interface is simplified, since we can now get the JSON string "result" information and load it as a Python dict:

```python
class JobResultFuture(Future):
    @interruptible
    def get_result(self):
        result_str = ffi.new("char *[1]")
        RAW.result_get(self.handle, result_str)
        if result_str[0] == ffi.NULL:
            return None
        result = json.loads(ffi.string(result_str[0]).decode("utf-8"))
        result["id"] = JobID(result["id"])
        return result
```

e.g.:
```python
#!/usr/bin/env python3

import sys
import json
import flux
from flux.job import JobspecV1

h = flux.Flux()
jobspec = JobspecV1.from_command(sys.argv[1:])
jobid = flux.job.submit(h, jobspec)
print(json.dumps(flux.job.result_async(h, jobid).get_result()))
```

```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py true | jq
{
  "id": 362134680633344,
  "result": 1,
  "started": 1,
  "status": 0,
  "exitcode": 0,
  "exception": 0
}
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py false | jq
{
  "id": 362223666987008,
  "result": 2,
  "started": 1,
  "status": 256,
  "exitcode": 1,
  "exception": 0
}
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ ./test.py foo | jq
{
  "id": 362335269027840,
  "result": 4,
  "started": 1,
  "status": 32512,
  "exitcode": 127,
  "exception": 1,
  "exception_type": "exec",
  "exception_note": "task 0: start failed: foo: No such file or directory",
  "exception_severity": 0
}
```

**Comment by grondo** [comment]
> I wonder if it would be useful to add a flags parameter to flux_job_result() to indicate how much detail is required? It might be possible to consolidate flux_job_wait() with this interface, or add other detail like stdio down the road. (Or maybe instead of integer mask of enum flags, a json_t array of key names would work better for bindings?)

Sorry I missed this comment originally.

Since the entire eventlog is read as part of the operation, I'm not sure there is any inherit benefit to introducing a flags or job-list like "array of attributes" to try to reduce the amount of information returned from this function. Accumulating these values is almost zero cost since strings like the exception type and note are stored without copying by taking an extra reference on the values in the eventlogs.

I'm not sure about collapsing this interface into `flux_job_wait(3)`, as it seems like they each serve a different purpose and trying to merge them would make the result work for neither case.

Finally, job output is from a different eventlog, so including that in this interface would also add extra complexity. Maybe a different function could be introduced in the future which combines the two in a convenience function. If that isn't really necessary from the C API it would be much easier to implement a convenience class in the Python bindings.

All that being said, I'm fine with adding a `flags` parameter to the function if you feel that might be useful down the road.

**Comment by grondo** [comment]
I've re-titled this PR appropriately and removed WIP since it is now in a somewhat merge-able state.

Some tests and documentation for the Python interface were added, which resulted in some other small fixes. The result was squashed down and force-pushed.

File: src/common/libjob/job.c [hunk 1]
```diff
@@ -658,6 +659,200 @@ int flux_job_id_encode (flux_jobid_t id,
...
+
+        if (statusobj == NULL
+            || exitcode == NULL
+            || json_unpack (context, "{s:i}", "status", &status) < 0
+            || json_integer_set (statusobj, status) < 0
+            || flux_job_event_watch_cancel (f) < 0)
+            goto error;
+
+        if (WIFSIGNALED (status))
+            json_integer_set (exitcode, WTERMSIG (status) + 128);
```
Comment (jameshcorbett) [inline src/common/libjob/job.c:768]: Is `-WTERMSIG (status)` not a good option? That's what `FluxExecutor` does and also what you did [here](https://github.com/grondo/flux-core/commit/4a361896b1af0cc8a1d7b2bbc158135dde4dc151). It's fine either way of course, it would just be good to be consistent.

File: src/common/libjob/job.c [hunk 2]
```diff
@@ -658,6 +659,200 @@ int flux_job_id_encode (flux_jobid_t id,
...
+    }
+    if ((result = json_object_get (res, "result")))
+        json_integer_set (result, job_result_calc (res));
+    s = json_dumps (res, JSON_COMPACT);
+    flux_future_fulfill_next (f, s, free);
+    flux_future_destroy (f);
+}
+
+static int job_result_handle_exception (json_t *res,
+                                        json_t *context)
```
Comment (jameshcorbett) [inline src/common/libjob/job.c:708]: What happens to duplicate exceptions, or multiple different exceptions?

I think it might be best to overwrite any previous exception data. The worst case is that a severity-1 exception would overwrite a severity-0 exception, but I think a severity-0 is guaranteed to be the last exception, if it occurs at all?

If that's already how it works, ignore this.

**Comment by jameshcorbett** [comment]
I gave it a try in Python and it works great! Thanks for implementing this @grondo !

One minor comment: I noticed that if you try to get the result for a bad jobid, you get `FileNotFoundError: [Errno 2] ENOENT: No such file or directory` which is a little weird. If it's easy (?) it might be worth changing to `EINVAL` or something. `flux.job.wait`is also a little strange for throwing `ChildProcessError: [Errno 10] invalid job id, or job may be inactive and not waitable` in the same situation, but the additional explanation helps a lot.

I thought at first that returning a dictionary with variable keys from `flux.job.result` was a little strange, but I couldn't think of anything better. If users want a simpler interface in the future, it would always be easy enough to add a helper function like:

```python

def returncode(result):
    if result["exception"] and result["exception_severity"] == 0:
        raise JobException(result["exception_note"])
    return result["exitcode"]
```

File: src/common/libjob/job.c (hunk 1 above)
Comment (grondo) [reply src/common/libjob/job.c:768]: Oh, sorry. This was adapted from existing code in `flux job status` which reports exit code in a way similar to the POSIX shell (128 + signal) if the function was terminated by a signal. I had forgotten about the `JobInfo` `returncode` property -- I think you are right, that is more useful here. We could also just add `returncode` in the Python interface.

File: src/common/libjob/job.c (hunk 2 above)
Comment (grondo) [reply src/common/libjob/job.c:708]: Good thought, the last exception will overwrite the previous one. There could also be multiple severity 0 exceptions, and nothing (currently) prevents a non-severity 0 exception from being entered into the eventlog after a severity 0 exception (though the sev 0 exception will cause job termination)

In the interest of keeping the interface simple, what if we documented that in the case of multiple exceptions only the latest, most severe exception is presented in the "result".

It also would not be too difficult to store the exceptions as an array, ordered by most severe, then timestamp. Then the `exception` member could record the number of exceptions in the eventlog. However, this would make the interface slightly less convenient in the common case.

**Comment by grondo** [comment]
> This is what I would use myself. It's a trivial function, but it might not be clear how to use the information in the dictionary.

This is a good point. I'm not well versed in Python interfaces so I'm happy to do whatever you want here. Feel free to suggest something if you'd like. Perhaps we can have a `JobResult` class with documented properties, including your `returncode` above?

**Comment by grondo** [comment]
Just because I had forgotten, the use of `-TERMSIG` in `returncode` is taken from Python [`subprocess.Popen.returncode`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode)

File: src/common/libjob/job.c (hunk 2 above)
Comment (jameshcorbett) [reply src/common/libjob/job.c:708]: > In the interest of keeping the interface simple, what if we documented that in the case of multiple exceptions only the latest, most severe exception is presented in the "result".

I like that solution. If you just care about the result of the job, it makes sense to only store the one exception that actually killed the job, and storing the latest and most severe exception is a good approximation to that. I think if users want to see all the exceptions that occurred, it would make more sense to just go through the eventlog entry by entry.

File: src/common/libjob/job.c (hunk 1 above)
Comment (jameshcorbett) [reply src/common/libjob/job.c:768]: Is it feasible to just remove the `exitcode` JSON attribute and make the two interfaces construct the value that makes the most sense locally? So that `flux job status` could return 128 + signum and Python could return -signum.

**Comment by jameshcorbett** [comment]
> This is a good point. I'm not well versed in Python interfaces so I'm happy to do whatever you want here. Feel free to suggest something if you'd like. Perhaps we can have a `JobResult` class with documented properties, including your `returncode` above?

I really think it is fine either way. One option would be to return a `collections.namedtuple` with three attributes: jobid, returncode integer/JobException instance, and then the original dictionary. I think the original dictionary should be exposed in case a user wants all the information (like whether the job started or a non-fatal exception occurred). The `namedtuple` approach has the advantage that it's kind of like how `job.wait` works.

@SteVwonder if you wanted to pitch in on this extremely pressing question, the information to present to users is:

```
 *   {
 *     "id":i,                 jobid
 *     "result:i,              flux_job_result_t
 *     "started":i,            1 if job had a 'start' event, 0 otherwise
 *     "status":i,             wait status if job started
 *     "exitcode":i,           decoded exit code if job started
 *     "exception":i,          1 if job had an exception, 0 otherwise
 *     "exception_severity"?i, exception severity (if exception)
 *     "exception_type"?s,     exception type (if exception)
 *     "exception_note"?s      exception note (if exception)
 *   }
 ```

File: src/common/libjob/job.c (hunk 1 above)
Comment (grondo) [reply src/common/libjob/job.c:768]: Yes, that is what I was thinking as well.

In fact, we could remove `exitcode`, rename `status` to `waitstatus` and `exception` to `exception_occurred` (and make it a boolean I think), and then the returned dict could be used to create a `JobInfo` object I think..

**Comment by grondo** [comment]
Thanks @jameshcorbett, fyi I'm out the rest of the week so may not be able to work on this until next week. FWIW, I'm fine with whatever you and @SteVwonder decide for Python API, though I think we're headed in a good direction with your suggestions above.

**Comment by SteVwonder** [comment]
> One option would be to return a collections.namedtuple with three attributes: jobid, returncode integer/JobException instance, and then the original dictionary.

That seems reasonable to me.  I'm a little iffy on having a mixed type of integer/JobException for the second tuple element.  Maybe there is a better way to do this, but this feels awkward to me:
```python
ret = wait.result(fh, jobid)
if isinstance(ret[1], Exception):
    print("Terrible things happened here")
    raise ret[1]
else:
    print(f"Job exited with exit code: {ret[1]}")
```

Do we want to split those into two separate elements?
```python
ret = wait.result(fh, jobid)
if ret[1] is not None
    print("Terrible things happened here")
    raise ret[1]
else:
    print(f"Job exited with exit code: {ret[2]}")
```

Side-note: We should make sure that the python bindings have access to the `flux_job_result_t` constants/enums (they should; `cffi` should pick them up automatically) and that they are documented (they don't appear to be).

I'm also OK with the `JobResult` class option too.

**Comment by grondo** [comment]
Ok, I have a work-in-progress change to this PR. Before I get any further (especially with testing), I wanted to get the ok on this new direction.

In the `flux_job_result(3)` "payload", `exitcode` and `started` are dropped,  `status` is changed to `waitstatus` and the job state timestamps `t_submit`, `t_run`, and `t_cleanup` are added. The exitcode can be computed as suggested by @jameshcorbett, and whether the job ran can be queried by checking for an existent `t_run` timestamp.

Furthermore, the resulting dictionary matches that used by the Python `JobInfo` class. A new `JobResult` class returned by `flux.job.wait.result()` can then use the `JobInfo` class to compute `returncode` instead of duplicating that code, e.g. a first cut `JobResult` class might be:

```python
class JobResult:
    """Class representing a job result obtained via :meth:`result`

    Attributes:
        dict (dict): Raw dictionary returned from ``flux_job_result(3)``
        info (:obj:`flux.job.info.JobInfo`)
        result (int): The job result (``flux_job_result_t``)
        returncode (int): The job returncode. The highest job shell exit
                          code or negative signal number if the job shell
                          was terminated by a signal. FOr jobs that were
                          canceled before the RUN state, the returncode
                          will be set to -128.
    """
    def __init__(self, resultdict):
        self.dict = resultdict
        self.info = JobInfo(self.dict)

    @property
    def result(self):
        return self.info.result_id

    @property
    def returncode(self):
        return self.info.returncode

```

I'm totally ambivalent on what is returned by the Python `get_result()` method though. If Python users really prefer named tuples to objects, we could implement that. I'm also not sure I fully understand where the interface should throw an exception. If you want, I could strip this PR down to just the C API and @jameshcorbett or @SteVwonder could submit a separate PR with the appropriate Python interface if I'm not even close..

**Comment by SteVwonder** [comment]
> Furthermore, the resulting dictionary matches that used by the Python JobInfo class. A new JobResult class returned by flux.job.wait.result() can then use the JobInfo class to compute returncode instead of duplicating that code, e.g. a first cut JobResult class might be:

Seems good to me.  Would it be too weird to just directly return a `JobInfo` instance?  I guess it would be fragile if we change the info returned by wait.result.

**Comment by jameshcorbett** [comment]
Yeah I agree it looks good, whether directly returning a `JobInfo` or instead the `JobResult` wrapper. My slight preference would be for a `returncode` method that raises an exception when the job didn't finish rather than returning -128, but that would require modifying `JobInfo`. And it's fine either way.

**Comment by grondo** [comment]
Hm, since it is simpler, I'll just change the `JobResultFuture` custom `get` method to `get_info()` and return a `JobInfo` object for now. For testing purposes I'll change the previous `get_result()` to `get_dict()` to offer a way to get the raw result dictionary.

**Comment by grondo** [comment]
Ok, done. `flux.job.wait.result` now returns a `JobInfo` object. This PR needs a fresh review.

**Comment by jameshcorbett** [comment]
I tried out the Python interface, and it looks and works great. Thanks @grondo !

**Review by SteVwonder — APPROVED** [review]
Python changes LGTM! Thanks @grondo!

**Comment by grondo** [comment]
I forgot to add an `int flags` parameter to `flux_job_result(3)` as requested by @garlick. I'll do that now. It should not change the python interface (except by adding a new optional `flags` parameter)

As @garlick notes, this could be handy in the future if a user wants to also grab other data along with the "result" (e.g. job output, exec eventlog timestamps).

**Comment by grondo** [comment]
Ok, I've changed the `flux_job_result(3)` prototype to:
```C
flux_future_t *flux_job_result (flux_t *h, flux_jobid_t id, int flags);
```
The `flags` parameter is currently unused.

File: src/common/libjob/job.c [hunk 3]
```diff
@@ -658,6 +659,218 @@ int flux_job_id_encode (flux_jobid_t id,
...
+
+    if (flux_future_get (f, NULL) < 0 && errno != ENODATA) {
+        flux_future_continue_error (f, errno, NULL);
+        flux_future_destroy (f);
+        return;
+    }
+    flux_job_result_t result = job_result_calc (res);
+    if (json_object_set_new (res,
+                             "result",
+                             json_integer (result)) < 0)
```
Comment (garlick) [inline src/common/libjob/job.c:704]: check for NULL return of `json_integer()`

is it ok to just return here if there is an error?

File: src/common/libjob/job.c [hunk 4]
```diff
@@ -658,6 +659,218 @@ int flux_job_id_encode (flux_jobid_t id,
...
+        return;
+    s = json_dumps (res, JSON_COMPACT);
```
Comment (garlick) [inline src/common/libjob/job.c:706]: check for NULL return of `json_dumps()`

**Review by garlick — APPROVED** [review]
Just a couple of minor comments - looks good!

File: src/common/libjob/job.c (hunk 3 above)
Comment (grondo) [reply src/common/libjob/job.c:704]: Good catch. The future should be fulfilled with an error on failure here.

**Comment by grondo** [comment]
Ok, force-pushed a change to address @garlick's comments (Thanks!) and will set MWP now.
