### PR TITLE
job-exec: improve cleanup after lost shell events

### LINKED ISSUE #5811: job-exec: job takes longer than necessary to terminate after a node failure
When the job-exec module handles a node failure on a critical rank it raises a job exception but does not also notify the rank 0 job shell that a shell has gone away. This causes the job shell to wait indefinitely in the output plugin for EOF from the missing shell.

This was partially fixed by #5780, but only for non-critical ranks.

### PR DESCRIPTION
**Pull request by grondo**
This PR fixes #5811 by always notifying the leader job shell of lost shells, whether they are critical or not. This then allows the leader shell to exit quickly when all its tasks terminate, rather than waiting for EOF from a lost shell during abnormal termination.

### CODE REVIEW

File: src/modules/job-exec/exec.c [hunk 1]
```diff
@@ -182,8 +183,11 @@ static int lost_shell (struct jobinfo *job,
         va_end (ap);
     }
 
-    if (raise_exception) {
-        /* Raise a non-fatal job exception */
+    if (!critical) {
+        /* Raise a non-fatal job exception if the lost shell was not critical.
+         * The job exec service will raise a fatal excception later for
```
Comment (chu11) [inline src/modules/job-exec/exec.c:188]: s/excception/exception/

File: src/modules/job-exec/exec.c [hunk 2]
```diff
@@ -227,21 +236,28 @@ static void error_cb (struct bulk_exec *exec, flux_subprocess_t *p, void *arg)
...
+            /*  Raise a fatal error and terminate job immediately if
+             *  the lost shell was critical.
+             */
+            if (critical)
+                jobinfo_fatal_error (job,
+                                     0,
+                                     "%s on broker %s (rank %d)",
+                                     "lost contact with job shell",
+                                     hostname,
+                                     rank);
```
Comment (chu11) [inline src/modules/job-exec/exec.c:260]: would it be useful to say "critical" somewhere in this message to differentiate it from the prior one?  Like "lost contact with critical job shell"?  I'm aware the messages are going to different places ... but might be useful when debugging?

**Review by chu11 — APPROVED** [review]
LGTM, just one typo and one minor message comment.

File: src/modules/job-exec/exec.c (hunk 2 above)
Comment (grondo) [reply src/modules/job-exec/exec.c:260]: Perhaps, though it is probably enough that the exception raised will be fatal.

Note that by far the common case is that all job shells are critical. Only in the case of a Flux instance (which adjusts its own critical ranks to remove the leaf broker rank), or if a user manually updates critical ranks will the non critical (severity 1) `lost-shell` exception be raised.

Because this is the common case, it might be less confusing to keep the error message to the user simpler, at least for now.

Comment (grondo) [reply src/modules/job-exec/exec.c:260]: Also, in case it wasn't obvious from the diff, this particular call didn't change from before, the code was just reorganized to also call `lost_shell()` for a critical rank loss.

**Comment by grondo** [comment]
I've fixed the typo and set MWP, thanks!
