### PR TITLE
sysmon: handle hybrid cgroup hierarchy

### LINKED ISSUE #7026: shell: `sysmon` shell plugin failure on system without unified cgroup hierarchy
I'm seeing these failures trying to use the `sysmon` shell plugin on my system without the unified cgroup hieararchy:
```console
$ flux run -o sysmon true
flux-job: ƒ2DFKqmYBvCF started                                         00:00:10
10.404s: job.exception ƒ2DFKqmYBvCF type=exec severity=0 shell_init
10.400s: flux-shell[0]: ERROR: sysmon: error caching cgroup paths
10.400s: flux-shell[0]: ERROR: plugin 'sysmon': shell.init failed
10.400s: flux-shell[0]: FATAL: shell_init
flux-job: task(s) exited with exit code 1
```

Probably expected that this won't work, but possibly the error message could use improvement. A minor issue.

### PR DESCRIPTION
**Pull request by garlick**
Problem: sysmon assumes the unfied cgroup hierarchy, but some modern systems use the hybrid hierarchy.
    
Use  cgroup support code pulled in from flux-security, as it handles the hybrid cgroup hierarchy
In addition, use some new cgroup helpers to parse `/sys` files instead of embedding one-offs.
    
Also, treat missing memory or cpu `/sys` files as non-fatal warnings, simply disabling one or the other with a warning message.
    
Fixes #7026

As extra credit later on, the oom plugin could be similarly converted.

### CODE REVIEW

File: src/common/libutil/cgroup.c [hunk 1]
```diff
@@ -43,9 +44,107 @@
...
+                              const char *key,
+                              const char *fmt,
+                              va_list ap)
+{
+    char path[PATH_MAX + 1];
+    FILE *fp;
+    char *line = NULL;
+    size_t size = 0;
+    int n;
+    int rc = -1;;
```
Comment (grondo) [inline src/common/libutil/cgroup.c]: extra semicolon

File: src/shell/sysmon.c [hunk 2]
```diff
@@ -15,6 +15,7 @@
 #if HAVE_CONFIG_H
 #include "config.h"
 #endif
+#include <sys/param.h>
```
Comment (grondo) [inline src/shell/sysmon.c:18]: commit message typo: unfied

File: src/common/libutil/cgroup.c (hunk 1 above)
Comment (garlick) [reply src/common/libutil/cgroup.c]: You can't be too careful.

**Comment by garlick** [comment]
Fix those typos and one caught by the typo checker, and fixed mac portability.

**Comment by garlick** [comment]
Setting MWP
