### PR TITLE
job-ingest: launch `.py` validators with configured python

### LINKED ISSUE #2491: Long python interpreter paths break `validate-shema.py.in`
`validate-schema.py.in` starts with `#!@PYTHON@`.   If the full path to the python interpreter that flux is configured with is >127 characters, it fails to exec (thanks to kernel limits).

```
→ head -n1 ./src/modules/job-ingest/validators/validate-schema.py                                                                                                                                                                                                │···········
#!/home/herbein1/Repositories/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.4.0/python-2.7.16-v4r2orsb2vj4zvawlln3npwe4vzntf3r/bin/python 
→ ./src/modules/job-ingest/validators/validate-schema.py                                                                                                                                                                                                     
zsh: ./src/modules/job-ingest/validators/validate-schema.py: bad interpreter: /home/herbein1/Repositories/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.4.0/python-2.7.16-v4r2orsb2vj4zvawlln3npwe4vzntf: no such file or directory
```

Switching the shebang to `#!/usr/bin/env flux-python` should fix this particular problem, but it may cause a regression to the problem seen in https://github.com/flux-framework/flux-core/issues/2434.

In it's current state, this file means we cannot run `spack install --test=root flux-core` for versions 0.12.0, 0.13.0, and master.

### PR DESCRIPTION
**Pull request by SteVwonder**
`validate-schema.py.in` was an autoconf input file with a `#!@PYTHON@`
template at the top of the file.  This ensured that the
`validate-schema.py` script always ran with the python interpreter that
Flux was configured with.  This works as long as the python interpreter
path is short enough.  When the path is > 127 characters, the script
fails to execute due to kernel limits.

Rename `validate-schema.py.in` to `validate-schema.py` and remove the
`#!@PYTHON@` template shebang line.  Update the `job-ingest` module to
launch validators ending with `.py` with the configured python
interpreter.  `job-ingest` executes other scripts as before.

Add a test to ensure that non-python executables can still be launched
as validators.

Fixes #2491

### CODE REVIEW

File: src/modules/job-ingest/validate.c [hunk 1]
```diff
@@ -74,13 +74,23 @@ void validate_destroy (struct validate *v)
...
 
+static inline bool str_ends_with (const char *str, const char *suffix)
+{
+    int str_len = strlen(str);
+    int suffix_len = strlen(suffix);
+
+    return (str_len >= suffix_len) && \
+        (!strncmp((str + str_len) - suffix_len, suffix, suffix_len));
+}
+
```
Comment (garlick) [inline src/modules/job-ingest/validate.c]: There should be a space between function names and open parens per RFC 7.

While you're in there, I'd probably drop the `inline` for consistency with the rest of the code base and because this is not performance critical code.

File: src/modules/job-ingest/validate.c [hunk 2]
```diff
@@ -89,15 +99,29 @@ struct validate *validate_create (flux_t *h,
...
+    } else {
+        argv[0] = (char *)validate_path,
+        argv[1] = "--schema";
+        argv[2] = (char *)schema_path,
+        argv[3] = NULL;
+        argv[4] = NULL;
+        argc = 3;
+        assert (argv[0] != NULL);
+        assert (argv[2] != NULL);
+    }
```
Comment (garlick) [inline src/modules/job-ingest/validate.c]: Suggestion to reduce code duplication (untested):
```c
assert (validate_path != NULL);
assert (schema_path != NULL);
argc=0;
if (str_ends_with (validate_path, ".py"))
    argv[argc++] = PYTHON_INTERPRETER;
argv[argc++] = (char *)validate_path;
argv[argc++] = "--schema";
argv[argc++] = (char *)schema_path,
argv[argc++] = NULL;
```

File: src/modules/job-ingest/validate.c (hunk 1 above)
Comment (SteVwonder) [reply src/modules/job-ingest/validate.c]: :+1:

File: src/modules/job-ingest/validate.c (hunk 2 above)
Comment (SteVwonder) [reply src/modules/job-ingest/validate.c]: Nice! The duplicated code bothered me as well, but I didn't think of `argc++`.  Done!

**Comment by garlick** [comment]
Thanks!
