### PR TITLE
Fix compilation under GCC 10.1.0

### LINKED ISSUE #2953: Compilation error under GCC 10.1.0
Posting this to make sure the patch passes the smell test before I post a PR.

Error
```
     636    make[3]: Entering directory '/tmp/sherbein/spack-stage/spack-stage-flux-core-0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/spack-build/src/modules/job-ingest'
     637      CC       job-ingest.lo
     638      CC       validate.lo
     639      CC       worker.lo
     640      CCLD     job-ingest.la
     641    /usr/bin/ld: .libs/validate.o:/tmp/sherbein/spack-stage/spack-stage-flux-core-0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/src/modules/job-ingest/validate.h:18: multiple definition of `v'; .libs/job-ingest.o:/tmp/sherbein/spack-stage/spack-stage-flux-core
            -0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/src/modules/job-ingest/validate.h:18: first defined here
  >> 642    collect2: error: ld returned 1 exit status
     643    make[3]: *** [Makefile:590: job-ingest.la] Error 1
     644    make[3]: Leaving directory '/tmp/sherbein/spack-stage/spack-stage-flux-core-0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/spack-build/src/modules/job-ingest'
     645    make[2]: *** [Makefile:509: all-recursive] Error 1
     646    make[2]: Leaving directory '/tmp/sherbein/spack-stage/spack-stage-flux-core-0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/spack-build/src/modules'
     647    make[1]: *** [Makefile:507: all-recursive] Error 1
     648    make[1]: Leaving directory '/tmp/sherbein/spack-stage/spack-stage-flux-core-0.16.0-2pt5mhql2yrkx3di5oibywcxn4paobsb/spack-src/spack-build/src'
```

validate.h:
```C
struct validate *v;

/* Submit jobspec ('buf, 'len') for validation.
 * Future is fulfilled once validation is complete.
 */
flux_future_t *validate_jobspec (struct validate *v, const char *buf, int len);
```

Applying this patch fixes the error:
```diff
diff --git a/src/modules/job-ingest/validate.h b/src/modules/job-ingest/validate.h
index e7fdd078a..2b36f387a 100644
--- a/src/modules/job-ingest/validate.h
+++ b/src/modules/job-ingest/validate.h
@@ -15,7 +15,7 @@

 #include "types.h"

-struct validate *v;
+struct validate;

 /* Submit jobspec ('buf, 'len') for validation.
  * Future is fulfilled once validation is complete.
```

### PR DESCRIPTION
**Pull request by SteVwonder**
The latest version of GCC reports two new errors.  One is a linker error due to duplicate declaration, and the other is a possible unintialized access due to an error condition that doesn't exit/return.

Also tossing in a small tweak to the valgrind suppression file to handle newer versions of `libdl` (a function changed names).

Closes #2953

### CODE REVIEW

File: src/cmd/flux-terminus.c [hunk 1]
```diff
@@ -192,8 +192,10 @@ int main (int argc, char *argv[])
         exit (1);
 
     if ((argc - optindex == 0)
-        || !optparse_get_subcommand (p, argv[optindex]))
+        || !optparse_get_subcommand (p, argv[optindex])) {
         optparse_fatal_usage (p, 1, NULL);
+        exit (1);
```
Comment (grondo) [inline src/cmd/flux-terminus.c:197]: Just curious what's going on here? `optparse_fatal_usage() doesn't return unless the fatalerr function is overridden so the `exit(1)` here *should* be dead code.

Comment (SteVwonder) [reply src/cmd/flux-terminus.c:197]: I believe the fact that the fatalerr function can be overridden to something that doesn't exit is what has GCC tied in knots.  It throws a warning (which gets elevated to an error) about code further down using potentially uninitialized variables.  You probably already saw, but the warning/error message from GCC is in the commit message. 

Rather than adding `exit (1);` here, I wonder if we can add some sort of pragma to the code to tell GCC to ignore any `maybe-uninitialized` warnings emanating from this code.  I feel like disabling `maybe-uninitialized` across the whole code base is too heavy-handed.

Thoughts?

Comment (chu11) [reply src/cmd/flux-terminus.c:197]: Would initializing `id` be a bad idea to get around this?

Comment (grondo) [reply src/cmd/flux-terminus.c:197]: yeah, want to try `__attribute__ ((noreturn))` to `optparse_fatal_usage()`?

Comment (grondo) [reply src/cmd/flux-terminus.c:197]: Though I guess you are right code could override the fatalerr function to actually return so that we can't put that attribute on the function with total confidence... maybe your fix is fine here. Thanks.

Comment (grondo) [reply src/cmd/flux-terminus.c:197]: > Would initializing id be a bad idea to get around this?

Sorry I missed this comment at first. That seems like a pragmatic suggestion @chu11

Comment (SteVwonder) [reply src/cmd/flux-terminus.c]: Thanks @grondo and @chu11!  Just replaced the commit with a commit that initializes `id` rather than adding `exit (1)`.

**Comment by grondo** [comment]
restarted CentOS 7 builder which died with
```
flux-start: 0 (pid 10518) Killed
1..17
ERROR: t1003-kvs-stress.t - exited with status 137 (terminated by signal 9?)
```

**Comment by garlick** [comment]
Late to the party but wanted to commend you for some really well formatted commit messages on this one @SteVwonder.  High quality - thank you!
